---

###
## roles controlM
## task  check
## purpose: check if controlM is installed and check version
##
## created by:    Nicolas VIDEAU For ITG/IPS/PPM02, 14/05/2018
## modifications: (name, date, purpose)
## Sylvain GRIVOT, 08/02/2019, ajout version des agents 
###
- set_fact:
    controlm_status: "OK"
- name: Check Control-M Agent version
  no_log: true
  block:
    - win_shell: Get-CTMAgent | Select-Object Agent,Install, FixPack -Unique | ConvertTo-Csv -Delimiter ';' -NoTypeInformation
      register: ctmCheck
      changed_when: False
    - set_fact:
        tmp_json: ""
      when: ctmCheck.stdout != "" 
    - set_fact:
        tmp_json: "{{ tmp_json }}, { \"agent_name\": {{ item.split(';')[0] }} ,\"install\": {{ item.split(';')[1] }},\"fix_pack\": {{ item.split(';')[2] }} }"
      with_items: "{{ ctmCheck.stdout_lines[1:] }}"
      when: ctmCheck.stdout != "" 
    - set_fact:
        controlm_value: '{ "installed": "yes" ,"version": [ {{ tmp_json[1:] }} ] }'
      when: ctmCheck.stdout != ""        
    - set_fact:
        controlm_value: '{ "installed": "no" ,"version": "" }'
      when: ctmCheck.stdout == ""     
  rescue:
    - set_fact:
        controlm_status: "KO"
        controlm_value: "unknown"
  always:
    - name: set result output for Check Control-M Agent version
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "info"
        set_results_item: ""
        set_results_value: "{{ controlm_value }}"
        set_results_component: "{{ controlm_component }}"
        set_results_operation: "{{ controlm_operation }}"
        set_results_role_name: "{{ controlm_role_name }}"
        set_results_result_name: "{{ controlm_result_name }}"
        set_results_script_mode: "{{ controlm_script_mode }}"
        set_results_status: "{{ controlm_status }}"

