---

###
## roles controlM
## task  check
## purpose: check if controlM is installed and check version
##
## created by:    Nicolas VIDEAU For ITG/IPS/PPM02, 14/05/2018
## modifications: (name, date, purpose)
## GRIVOT Sylvain, 08/02/2019, ajout version des agents 
###


- set_fact:
    controlm_status: "OK"
- name: Check Control-M Agent version
  no_log: true
  block:
    - shell: "for ctm_info in $(grep ctm /etc/passwd | sed 's/ //g'); do ctm_path=$(echo ${ctm_info} | awk -F : '{print $6}'); CM_account=$(echo ${ctm_info} | awk -F : '{print $1}'); if [ -f ${ctm_path}/ctm/scripts/ag_diag_comm ];then CM_Version=$(cat ${ctm_path}/installed-versions.txt | grep Agent | awk '{print $5}'| sort -u |tail -1); echo \"${CM_account};${CM_Version}\"; fi; done"
      register: ctmList
      changed_when: false
    - set_fact:
        tmp_json: ""
    - set_fact:
        tmp_json: "{{ tmp_json }}, { \"accountname\": \"{{ item.split(';')[0] }}\" ,\"install_with_fix_pack\": \"{{ item.split(';')[1] }}\" }"
      when:  ctmList.stdout_lines != ""
      with_items: "{{ ctmList.stdout_lines }}"
    - set_fact:
        controlm_value: '{ "installed": "yes" ,"version": [ {{ tmp_json[1:] }} ] }'
      when: tmp_json != ""   
    - set_fact:
        controlm_value: '{ "installed": "no" ,"version": "" }'
      when: tmp_json == ""     
  rescue:
    - set_fact:
        controlm_status: "KO"
        controlm_value: "unknown"
  always:
    - name: set result output for Check Control-M Agent version
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "info"
        set_results_item: ""
        set_results_value: "{{ controlm_value }}"
        set_results_component: "{{ controlm_component }}"
        set_results_operation: "{{ controlm_operation }}"
        set_results_role_name: "{{ controlm_role_name }}"
        set_results_result_name: "{{ controlm_result_name }}"
        set_results_script_mode: "{{ controlm_script_mode }}"
        set_results_status: "{{ controlm_status }}"

