---

- set_fact:
    controlm_status: "OK"
    controlm_value: ""
    controlm_state: "listed"
- name: List Control-M Agent
  no_log: true
  block:
    - shell: "grep ctm /etc/passwd |awk -F : '{print $6}'"
      register: ctmList
      changed_when: false
    - stat:
        path: "{{ item }}/ctm/scripts/ag_diag_comm"
      register: ctmListFolders
      with_items: "{{ ctmList.stdout_lines }}"
      when: ctmList.stdout != ""
    - set_fact: ctmListUsers="{{ ctmListUsers|default([]) + [ item.stat.pw_name ] }}"
      when: item.stat.exists
      with_items: "{{ ctmListFolders.results }}"
      ignore_errors: yes
    - set_fact:
        controlm_value: "{{ ctmListUsers }}"
      when: ctmListUsers is defined
    - set_fact:
        controlm_value: "no user found"
      when: ctmListUsers is not defined
  rescue:
    - set_fact:
        controlm_status: "KO"
        controlm_value: "unknown"
        controlm_state: "not listed"
  always:
    - name: set result output for list Control-M Agent
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "{{ controlm_state }}"
        set_results_item: ""
        set_results_value: "{{ controlm_value }}"
        set_results_component: "{{ controlm_component }}"
        set_results_operation: "{{ controlm_operation }}"
        set_results_role_name: "{{ controlm_role_name }}"
        set_results_result_name: "{{ controlm_result_name }}"
        set_results_script_mode: "{{ controlm_script_mode }}"
        set_results_status: "{{ controlm_status }}"


