---

- name: Test If Control-M Agent is installed
  shell: grep {{ controlm_agentaccount }} /etc/passwd |wc -l
  register: isctmag
  changed_when: false
##########################################
- name: stop {{ controlm_agentaccount }}
  shell: ~{{ controlm_agentaccount }}/ctm/scripts/shut-ag -u {{ controlm_agentaccount }} -p all
  register: stopctmagent
  ignore_errors: yes
  changed_when: '"Listener process stopped" and "Tracker process stopped" in stopctmagent.stdout'
  when:
    - isctmag.stdout_lines[0]|int  == 1
##########################################
- name: check if  {{ controlm_agentaccount }} is stopped
  shell: ps -ef |grep -i {{ controlm_agentaccount }} |grep -v grep |wc -l
  register: checkctmag
  ignore_errors: yes
  changed_when: false
##########################################
- name: set results for stop {{ controlm_agentaccount }}
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state:
    "{% if checkctmag.stdout[0]|int == 0 and isctmag.stdout_lines[0]|int == 1 %}\

        stopped\

      {% else %}\

        not stopped\

      {% endif %}"
    set_results_item: "{{ controlm_agentaccount }}"
    set_results_component: "{{ controlm_component }}"
    set_results_operation: "{{ controlm_operation }}"
    set_results_role_name: "{{ controlm_role_name }}"
    set_results_result_name: "{{ controlm_result_name }}"
    set_results_value: ""
    set_results_status:
    "{% if '{{ controlm_agentaccount }}' is defined %}\

        OK\

      {% else %}\

        KO\

      {% endif %}"

