---
# Manage Nimsoft policies and profiles

- name: List current policies
  command: "{{ nimsoft.robot_path }}/controller -list_policies"
  register: current_policies
  changed_when: false

- name: Display current policies
  debug:
    msg: "{{ current_policies.stdout_lines }}"

- name: Apply policy
  command: "{{ nimsoft.robot_path }}/controller -apply_policy {{ policy_name }}"
  when:
    - policy_action == 'apply'
    - policy_name is defined
  register: policy_applied

- name: Remove policy
  command: "{{ nimsoft.robot_path }}/controller -remove_policy {{ policy_name }}"
  when:
    - policy_action == 'remove'
    - policy_name is defined
  register: policy_removed
