---
# Update Nimsoft probes and scripts

- name: Stop Nimsoft robot
  command: "{{ nimsoft.robot_path }}/controller -stop"
  register: nimsoft_stopped

- name: Update Nimsoft probes
  copy:
    src: "{{ item }}"
    dest: "{{ nimsoft.probe_path }}/"
    mode: '0755'
  loop: "{{ probe_files }}"
  when: probe_files is defined

- name: Start Nimsoft robot
  command: "{{ nimsoft.robot_path }}/controller -start"
  register: nimsoft_started

- name: Verify Nimsoft is running
  command: "{{ nimsoft.robot_path }}/controller -status"
  register: nimsoft_verify
  changed_when: false

- name: Display update status
  debug:
    msg: "Nimsoft updated and restarted successfully"
