---

- name: "Vérification de l'existence du répertoire /etc"
  ansible.builtin.stat:
    path: "/etc"
  register: etc_dir_check

- name: "Affichage du statut de vérification"
  ansible.builtin.debug:
    msg:
      - "=== Création de la bannière de connexion ==="
      - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "Hostname: {{ ansible_hostname }}"
      - "Environnement: {{ environnement | default('PRODUCTION') }}"

- name: "Génération de la bannière MOTD (Message Of The Day)"
  ansible.builtin.template:
    src: "motd.j2"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: motd_creation

- name: "Génération de la bannière pre-login (issue)"
  ansible.builtin.template:
    src: "issue.j2"
    dest: "/etc/issue"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: issue_creation

- name: "Génération de la bannière pre-login réseau (issue.net)"
  ansible.builtin.template:
    src: "issue.j2"
    dest: "/etc/issue.net"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: issue_net_creation

- name: "Configuration SSH pour afficher la bannière"
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^#?Banner"
    line: "Banner /etc/issue.net"
    state: present
    backup: yes
  register: sshd_banner_config
  notify: "Restart sshd"

- name: "Vérification de la création des bannières"
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "/etc/motd"
    - "/etc/issue"
    - "/etc/issue.net"
  register: banner_files_check

- name: "Affichage du résultat de création des bannières"
  ansible.builtin.debug:
    msg:
      - "=== Résultat création bannières ==="
      - "MOTD créé: {{ 'OUI ✅' if motd_creation is changed else 'Déjà existant' }}"
      - "Issue créé: {{ 'OUI ✅' if issue_creation is changed else 'Déjà existant' }}"
      - "Issue.net créé: {{ 'OUI ✅' if issue_net_creation is changed else 'Déjà existant' }}"
      - "SSH configuré: {{ 'OUI ✅' if sshd_banner_config is changed else 'Déjà configuré' }}"

- name: "Lecture du contenu de la bannière MOTD"
  ansible.builtin.command: cat /etc/motd
  register: motd_content
  changed_when: false

- name: "Affichage de la bannière créée"
  ansible.builtin.debug:
    msg: "{{ motd_content.stdout_lines }}"

- name: "Enregistrement du résultat de création de bannière"
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "created"
    set_results_item: "banner"
    set_results_value: "Bannières créées: /etc/motd, /etc/issue, /etc/issue.net"
    set_results_component: "{{ banner_component | default('banner') }}"
    set_results_operation: "{{ banner_operation | default('create') }}"
    set_results_role_name: "{{ banner_role_name | default('ips_toolbox_banner') }}"
    set_results_result_name: "{{ banner_result_name | default('banner_creation') }}"
    set_results_status: "OK"
  ignore_errors: yes

