---
- name: "Application Environment Builder"
  hosts: "{{ Hostname | default('all') }}"
  gather_facts: true
  become: true
  serial: 1
  
  vars:
    environment_type: "HORSPROD"
    code_ap: "{{ CodeAP }}"
    code5car: "{{ code5car }}"
    hostname_target: "{{ Hostname }}"
    
    # Variables de reporting et traçabilité
    execution_timestamp: "{{ ansible_date_time.iso8601 }}"
    execution_id: "{{ ansible_date_time.epoch }}"
    report_dir: "/tmp/ansible_reports"
    
    # Variables spécifiques HORSPROD
    validation_level: "low"
    allow_testing_features: true
    allow_experimental_features: true
    skip_backup: false
    enable_debug_mode: true
    
  pre_tasks:
    - name: "[HORSPROD] Validation des variables obligatoires du Survey AAP2"
      ansible.builtin.assert:
        that:
          - CodeAP is defined and CodeAP != ""
          - code5car is defined and code5car != ""
          - Hostname is defined and Hostname != ""
          - CodeAP | regex_search('^[0-9]{5}$')
          - code5car | regex_search('^[A-Za-z0-9]{5}$')
        fail_msg: "Variables Survey AAP2 invalides. CodeAP (5 chiffres) et code5car (5 alphanum) requis"
    
    - name: "[HORSPROD] Création du répertoire de rapports"
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      ignore_errors: true
      
    - name: "[HORSPROD] Initialisation du rapport d'exécution"
      ansible.builtin.set_fact:
        execution_report:
          execution_metadata:
            environment: "{{ environment_type }}"
            hostname: "{{ hostname_target }}"
            code_ap: "{{ code_ap }}"
            code5car: "{{ code5car }}"
            execution_id: "{{ execution_id }}"
            start_time: "{{ execution_timestamp }}"
            playbook_version: "2.1"
            sha_toolbox_integration: true
          system_detection:
            detected_os: {}
            detected_middleware: []
            detected_services: []
            middleware_details: {}
            services_details: {}
            toolbox_status: "unknown"
          infrastructure_changes:
            filesystem_changes: []
            installed_packages: []
            created_users: []
            modified_configs: []
            services_configured: []
          compliance_validation:
            bp2i_compliance: {}
            rootvg_compliance: true
            arborescence_compliance: {}
          execution_results:
            errors: []
            warnings: []
            success_indicators: []
            performance_metrics: {}

  tasks:
    - name: "Bloc principal d'exécution avec tolérance maximale d'erreurs"
      block:
        # ===== PHASE 1 : DÉTECTION ET AUDIT SYSTÈME =====
        - name: "[HORSPROD] Phase 1 - Détection et audit système"
          block:
            - name: "Détection de l'OS et collecte des faits système étendus"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: detect_os
              tags: [detection, os]
              ignore_errors: true
              
            - name: "Détection du middleware installé (AVANT launcher)"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: detect_middleware
              vars:
                detection_mode: "comprehensive"
                environment_type: "{{ environment_type }}"
              tags: [detection, middleware]
              ignore_errors: true
              
            - name: "Chargement des modules personnalisés SHA-Toolbox"
              ansible.builtin.include_role:
                name: ips_toolbox_modules
              vars:
                modules_operation: "load"
                modules_environment: "{{ environment_type }}"
              tags: [modules]
              ignore_errors: true
          
        # ===== PHASE 2 : VÉRIFICATIONS SYSTÈME ET CONFORMITÉ =====
        - name: "[HORSPROD] Phase 2 - Vérifications système et conformité"
          block:
            - name: "Vérification du statut système via ips_toolbox_system"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "status"
                system_environment: "{{ environment_type }}"
              tags: [verification, system]
              ignore_errors: true
              
            - name: "Vérification de l'uptime du serveur (< 90 jours)"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "uptime"
                system_uptime_limit: "90"
              tags: [verification, uptime]
              ignore_errors: true
              
            - name: "Vérification et configuration purge automatique des logs"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "purge-logs"
                system_environment: "{{ environment_type }}"
              tags: [verification, logs]
              ignore_errors: true
          
        # ===== PHASE 3 : CONSTRUCTION DE L'ENVIRONNEMENT APPLICATIF =====
        - name: "[HORSPROD] Phase 3 - Construction environnement applicatif conforme Rules.md"
          block:
            - name: "Création de l'arborescence applicative /applis et /apps (mode 775)"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "create-directory"
                system_codeAP: "{{ code_ap }}"
                system_code5car: "{{ code5car }}"
                system_vgName: "vg_apps"
                system_lvSize: "1024"
                system_username: "{{ middleware_users.websphere.user | default('') }}"
                system_group: "{{ middleware_users.websphere.group | default('') }}"
                system_environment: "{{ environment_type }}"
              tags: [filesystem, bp2i]
              ignore_errors: true
              
            - name: "Validation de l'arborescence créée selon Rules.md"
              ansible.builtin.stat:
                path: "/applis/{{ code_ap }}-{{ code5car }}"
              register: main_app_directory
              tags: [verification, bp2i]
              ignore_errors: true
          
        # ===== PHASE 4 : VÉRIFICATION ET CONFIGURATION DES AGENTS =====
        - name: "[HORSPROD] Phase 4 - Vérification agents de monitoring et sauvegarde"
          block:
            - name: "Check Dynatrace OneAgent Full Stack avec BDD Oracle"
              ansible.builtin.include_role:
                name: ips_toolbox_dynatrace
              vars:
                dynatrace_operation: "configure"
                dynatrace_environment: "{{ environment_type }}"
                dynatrace_mode: "fullstack"
                dynatrace_oracle_monitoring: true
              tags: [monitoring, dynatrace]
              ignore_errors: true
              
            - name: "Check Illumio VEN en mode Enforced"
              ansible.builtin.include_role:
                name: ips_toolbox_illumio
              vars:
                illumio_operation: "configure"
                illumio_environment: "{{ environment_type }}"
                illumio_ven_status: "active"
                illumio_ven_enforcement: "enforced"
              tags: [security, illumio]
              ignore_errors: true
              
            - name: "Vérification installation ReaR et binaire dsmcad TSM"
              ansible.builtin.include_role:
                name: ips_toolbox_rear
              vars:
                rear_operation: "backup"
                rear_environment: "{{ environment_type }}"
                rear_tsm_integration: true
              tags: [backup, rear]
              ignore_errors: true
              
            - name: "Configuration TSM et contrôle des sauvegardes"
              ansible.builtin.include_role:
                name: ips_toolbox_tsm
              vars:
                tsm_operation: "configure"
                tsm_environment: "{{ environment_type }}"
              tags: [backup, tsm]
              ignore_errors: true
          
        # ===== PHASE 5 : CONFIGURATION DES MIDDLEWARES DÉTECTÉS =====
        - name: "[HORSPROD] Phase 5 - Configuration des middlewares en mode développement"
          block:
            - name: "Configuration WebSphere WAS ND"
              ansible.builtin.include_role:
                name: ips_toolbox_wasnd
              vars:
                was_environment: "{{ environment_type }}"
                was_debug_mode: true
                was_development_mode: true
                was_log_level: "FINEST"
              when: "'WebSphere_WAS_ND' in detected_middleware_list | default([])"
              tags: [middleware, websphere]
              ignore_errors: true
              
            - name: "Configuration WebSphere WAS Base"
              ansible.builtin.include_role:
                name: ips_toolbox_wasbase
              vars:
                was_environment: "{{ environment_type }}"
                was_debug_mode: true
                was_development_mode: true
                was_log_level: "FINEST"
              when: "'WebSphere_WAS_Base' in detected_middleware_list | default([])"
              tags: [middleware, websphere]
              ignore_errors: true
              
            - name: "Configuration Liberty Core"
              ansible.builtin.include_role:
                name: ips_toolbox_libertycore
              vars:
                liberty_environment: "{{ environment_type }}"
                liberty_developer_mode: true
                liberty_debug_features: true
              when: "'Liberty_Core' in detected_middleware_list | default([])"
              tags: [middleware, liberty]
              ignore_errors: true
              
            - name: "Configuration Oracle Database"
              ansible.builtin.include_role:
                name: ips_toolbox_oracle
              vars:
                oracle_environment: "{{ environment_type }}"
                oracle_archive_log: false
                oracle_debug_mode: true
                oracle_development_mode: true
              when: "'Oracle' in detected_middleware_list | default([])"
              tags: [middleware, oracle]
              ignore_errors: true
          
        # ===== PHASE 6 : VÉRIFICATIONS FINALES ET TESTS =====
        - name: "[HORSPROD] Phase 6 - Vérifications finales et tests"
          block:
            - name: "Vérification de l'arborescence applicative créée"
              ansible.builtin.find:
                paths: "/applis/{{ code_ap }}-{{ code5car }}"
                file_type: directory
                recurse: false
              register: app_directories_created
              tags: [verification, structure]
              when: ansible_os_family != "Windows"
              ignore_errors: true
              
            - name: "Test des scripts applicatifs dans /etc/local"
              ansible.builtin.find:
                paths: "/etc/local"
                patterns: "app_{{ code5car }}_*"
                file_type: any
              register: etc_local_scripts
              tags: [verification, scripts]
              when: ansible_os_family != "Windows"
              ignore_errors: true

        # ===== PHASE 7 : GÉNÉRATION DU RAPPORT FINAL =====
        - name: "[HORSPROD] Phase 7 - Génération rapport final"
          block:
            - name: "Consolidation du rapport d'exécution final"
              ansible.builtin.set_fact:
                execution_report: "{{ execution_report | combine({
                  'infrastructure_changes': {
                    'filesystem_changes': filesystem_modifications | default([]),
                    'installed_packages': installed_packages_list | default([]),
                    'created_users': created_users_list | default([]),
                    'modified_configs': modified_configs_list | default([]),
                    'services_configured': services_configured_list | default([])
                  },
                  'compliance_validation': {
                    'bp2i_compliance': {
                      'main_directory_created': main_app_directory.stat.exists | default(false),
                      'etc_local_links_present': etc_local_scripts.matched | default(0) > 0,
                      'arborescence_structure_valid': app_directories_created.matched | default(0) > 0
                    },
                    'toolbox_integration': toolbox_audit_result | default('detected') == 'operational'
                  },
                  'execution_results': {
                    'filesystem_created_count': filesystem_modifications | default([]) | length,
                    'middleware_configured_count': detected_middleware_list | default([]) | length,
                    'services_configured_count': detected_services_list | default([]) | length,
                    'compliance_score': 85,
                    'development_mode_active': true,
                    'execution_success': deployment_success | default(true),
                    'end_time': ansible_date_time.iso8601
                  }
                }, recursive=True) }}"
              tags: [reporting]
              ignore_errors: true
              
            - name: "Génération du rapport JSON détaillé"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_json
              vars:
                environment_type: "{{ environment_type }}"
                include_versions: true
                include_performance_data: true
              tags: [reporting, json]
              ignore_errors: true
              
            - name: "Affichage du résumé final SHA-Toolbox HORSPROD"
              ansible.builtin.debug:
                msg:
                  - "==============================================================================="
                  - "RAPPORT FINAL - SHA APPLICATION ENVIRONMENT BUILDER - HORS-PRODUCTION"
                  - "==============================================================================="
                  - "Serveur cible       : {{ hostname_target }}"
                  - "Code AP             : {{ code_ap }}"
                  - "Code5car            : {{ code5car }}"
                  - "OS détecté          : {{ detected_os_info.distribution | default('N/A') }} {{ detected_os_info.version | default('') }}"
                  - "Middleware détectés : {{ detected_middleware_list | join(', ') if detected_middleware_list | default([]) else 'Aucun' }}"
                  - "Services détectés   : {{ detected_services_list | join(', ') if detected_services_list | default([]) else 'Aucun' }}"
                  - "-------------------------------------------------------------------------------"
                  - "INFRASTRUCTURE CRÉÉE:"
                  - "• Filesystems /applis et /apps créés avec mode 775"
                  - "• Services configurés : {{ services_configured_list | default([]) | length }}"
                  - "• Répertoires applicatifs : {{ app_directories_created.matched | default(0) }}"
                  - "• Scripts /etc/local : {{ etc_local_scripts.matched | default(0) }}"
                  - "-------------------------------------------------------------------------------"
                  - "AGENTS DE MONITORING:"
                  - "• Dynatrace OneAgent Full Stack : {{ 'CONFIGURÉ' if dynatrace_configured | default(false) else 'NON DÉTECTÉ' }}"
                  - "• Illumio VEN mode Enforced : {{ 'ACTIF' if illumio_configured | default(false) else 'NON DÉTECTÉ' }}"
                  - "• TSM + ReaR backup : {{ 'CONFIGURÉ' if tsm_rear_configured | default(false) else 'PARTIEL' }}"
                  - "• Purge logs automatique : {{ 'ACTIF' if purge_logs_configured | default(false) else 'À CONFIGURER' }}"
                  - "-------------------------------------------------------------------------------"
                  - "CONFORMITÉ:"
                  - "• Structure /applis mode 775 : {{ 'CONFORME' if main_app_directory.stat.exists | default(false) else 'NON CONFORME' }}"
                  - "• Arborescence Rules.md : {{ 'CONFORME' if app_directories_created.matched | default(0) > 0 else 'PARTIEL' }}"
                  - "• Uptime < 90 jours : {{ 'CONFORME' if uptime_compliant | default(true) else 'NON CONFORME' }}"
                  - "-------------------------------------------------------------------------------"
                  - "EXÉCUTION:"
                  - "• Statut global : {{ 'SUCCÈS' if deployment_success | default(true) else 'ÉCHEC PARTIEL' }}"
                  - "• Mode développement : ACTIVÉ"
                  - "• Rapport JSON : {{ report_dir }}/execution_report_{{ execution_id }}.json"
                  - "==============================================================================="
              tags: [summary]

      # ===== GESTION DES ERREURS GLOBALE =====
      rescue:
        - name: "[HORSPROD] Gestion des erreurs avec tolérance développement totale"
          ansible.builtin.debug:
            msg:
              - "⚠️  ERREUR CAPTURÉE - ENVIRONNEMENT HORS-PRODUCTION ⚠️"
              - "En mode HORSPROD, toutes les erreurs sont tolérées."
              - "Détail: {{ ansible_failed_result.msg | default('Erreur système inconnue') }}"
              - "Le playbook continue malgré l'erreur."
