# playbooks/backup.yml
---
- name: "Backup Module Tasks"
  block:
    - name: "Execute TSM backup"
      include_role:
        name: ips_toolbox_tsm
      vars:
        tsm_operation: "backup"
      tags: backup

    - name: "Execute system backup"
      include_role:
        name: ips_toolbox_backup
      vars:
        backup_operation: "execute"
      tags: backup

  rescue:
    - name: "Backup module error handler"
      ansible.builtin.debug:
        msg:
          - "Error in Backup module"
          - "Task: {{ ansible_failed_task.name }}"
