---
- name: Database Module Tasks
  hosts: "{{ target_hostname }}"
  gather_facts: yes
  become: yes

  tasks:
    - name: Check Oracle presence
      stat:
        path: "{{ oracle.oratab_path }}"
      register: db_check

    - name: Set toolbox vars
      set_fact:
        toolboxes_component: "database"
        toolboxes_operation: "oracle"
        toolboxes_role_name: "ips_toolbox_oracle"
        toolboxes_task_file_name: "oracle.yml"

    - name: Execute database toolbox
      include_role:
        name: ips_toolbox_oracle
      when: db_check.stat.exists

  rescue:
    - name: Report database error
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "error"
        set_results_component: "database"
        set_results_operation: "oracle"
        set_results_role_name: "ips_toolbox_oracle"
        set_results_status: "KO"
        set_results_value: "Database module failed"
