# playbooks/database.yml
---
- name: "Database Module Tasks"
  block:
    - name: "Check and configure Oracle"
      include_role:
        name: ips_toolbox_oracle
      vars:
        oracle_operation: "configure"
      when: configure_oracle_db | bool
      tags: database

    - name: "Check and configure SQL Server"
      include_role:
        name: ips_toolbox_sqlserver
      vars:
        sqlserver_operation: "configure"
      when: ansible_os_family == "Windows"
      tags: database

  rescue:
    - name: "Database module error handler"
      ansible.builtin.debug:
        msg:
          - "Error in Database module"
          - "Task: {{ ansible_failed_task.name }}"
