---
- name: Operating Module Tasks
  hosts: "{{ target_hostname }}"
  gather_facts: yes
  become: yes

  tasks:
    - name: Set default operation
      set_fact:
        operation_type: "{{ operation }}"

    - name: Set toolbox vars
      set_fact:
        toolboxes_component: "system"
        toolboxes_operation: "{{ operation_type }}"
        toolboxes_role_name: "ips_toolbox_system"
        toolboxes_task_file_name: "{{ operation_type }}.yml"

    - name: Execute system toolbox
      include_role:
        name: "{{ toolboxes_role_name }}"
      vars:
        toolboxes_component: "{{ toolboxes_component }}"
        toolboxes_operation: "{{ toolboxes_operation }}"
        toolboxes_role_name: "{{ toolboxes_role_name }}"
        toolboxes_task_file_name: "{{ toolboxes_task_file_name }}"

  rescue:
    - name: Report operating error
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "error"
        set_results_component: "system"
        set_results_operation: "{{ operation_type }}"
        set_results_role_name: "ips_toolbox_system"
        set_results_status: "KO"
        set_results_value: "Operating module failed"
