# playbooks/operating.yml
---
- name: "Operating Module Tasks"
  block:
    - name: "Phase 1: Toolbox validation"
      include_role:
        name: ips_toolbox_toolboxes
      vars:
        toolboxes_operation: "check"
      tags: toolbox_validation

    - name: "Phase 2: SHA foundation validation"
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_operation: "validate"
      tags: sha_validation

    - name: "Phase 3: Filesystem creation"
      include_role:
        name: ips_toolbox_system
      vars:
        filesystem_action: create
      tags: fs_creation

    - name: "Phase 4: Application arborescence"
      include_role:
        name: ips_toolbox_system
      vars:
        create_arborescence: true
      tags: dir_structure

    - name: "Phase 5: Log rotation"
      include_role:
        name: ips_toolbox_system
      vars:
        manage_log_rotation: true
      tags: logs

  rescue:
    - name: "Operating module error handler"
      ansible.builtin.debug:
        msg:
          - "Error in Operating module"
          - "Task: {{ ansible_failed_task.name }}"
