---
# Web Module Playbook
# WebSphere and IHS management

- name: Web Module Tasks
  block:
    - name: Detect WebSphere type
      shell: |
        if [ -f "{{ websphere.profile_root }}/bin/server" ]; then
          echo "liberty"
        elif [ -f "{{ websphere.profile_root }}/bin/startServer.sh" ]; then
          echo "was"
        else
          echo "none"
        fi
      register: was_type_detected
      changed_when: false

    - name: Set WebSphere type
      set_fact:
        detected_was_type: "{{ was_type_detected.stdout }}"

    - name: Manage Liberty Core servers
      include_role:
        name: ips_toolbox_libertycore
      when:
        - detected_was_type == 'liberty'
        - was_variant | default('core') == 'core'
      tags:
        - liberty
        - libertycore

    - name: Manage Liberty Base servers
      include_role:
        name: ips_toolbox_libertybase
      when:
        - detected_was_type == 'liberty'
        - was_variant | default('base') == 'base'
      tags:
        - liberty
        - libertybase

    - name: Manage WAS ND servers
      include_role:
        name: ips_toolbox_wasnd
      when:
        - detected_was_type == 'was'
        - was_variant | default('nd') == 'nd'
      tags:
        - was
        - wasnd

    - name: Manage WAS Base servers
      include_role:
        name: ips_toolbox_wasbase
      when:
        - detected_was_type == 'was'
        - was_variant | default('base') == 'base'
      tags:
        - was
        - wasbase

    - name: Manage IHS (IBM HTTP Server)
      include_role:
        name: ips_toolbox_webserver
      when: manage_ihs | default(true) | bool
      tags:
        - ihs
        - webserver

  rescue:
    - name: Web module error handler
      debug:
        msg:
          - "Error occurred in Web module"
          - "Task: {{ ansible_failed_task.name }}"
          - "Error: {{ ansible_failed_result.msg | default('Unknown error') }}"
