# playbooks/web.yml
---
- name: "Web Module Tasks"
  block:
    - name: "Deploy to WAS ND"
      include_role:
        name: ips_toolbox_wasnd
      vars:
        wasnd_operation: "deploy-app"
      when: "'wasnd' in detected_middleware"
      tags: web

    - name: "Deploy to WAS Base"
      include_role:
        name: ips_toolbox_wasbase
      vars:
        wasbase_operation: "deploy-app"
      when: "'wasbase' in detected_middleware"
      tags: web

    - name: "Deploy to Liberty Core"
      include_role:
        name: ips_toolbox_libertycore
      vars:
        libertycore_operation: "deploy-app"
      when: "'libertycore' in detected_middleware"
      tags: web

    - name: "Configure WebServer"
      include_role:
        name: ips_toolbox_webserver
      vars:
        webserver_operation: "configure"
      when: "'webserver' in detected_middleware"
      tags: web

  rescue:
    - name: "Web module error handler"
      ansible.builtin.debug:
        msg:
          - "Error in Web module"
          - "Task: {{ ansible_failed_task.name }}"
