---
- name: Start Illumio agent
  ansible.builtin.command:
    cmd: "{{ services.illumio.paths.agent }} start"
  become: true
  register: illumio_start
  changed_when: illumio_start.rc == 0

- name: Enable Illumio agent to start on boot
  ansible.builtin.systemd:
    name: illumio-ven
    enabled: yes
  become: true

- name: Check status of illumio if present
  block:
    - name: Get status of illumio agent
      command: "{{ services.illumio.paths.agent }} status"
      register: illumio_status
      ignore_errors: yes

    - name: Debug illumio status
      debug:
        var: illumio_status

    - name: Check if enforced
      fail:
        msg: "Illumio is not enforced."
      when: "'enforced' not in illumio_status.stdout"

    - name: Set success illumio output var
      set_fact:
        services_illumio:
          output: "Illumio for {{ inventory_hostname }} successfully enforced"
          enforced: true
  rescue:
    - name: Illumio is not installed
      fail:
        msg: "Illumio is not installed."
      when: illumio_status.rc != 0

    - name: Illumio is not enforced
      fail:
        msg: "Illumio is not enforced."
      when: "'enforced' not in illumio_status.stdout"
