---
- name: "Initialisation du rôle ips_toolbox_toolboxes"
  ansible.builtin.set_fact:
    toolboxes_component: "toolboxes"
    toolboxes_role_name: "ips_toolbox_toolboxes"

- name: "Construction du nom de fichier de tâche toolboxes"
  ansible.builtin.set_fact:
    toolboxes_task_file: "{{ toolboxes_operation | default('verify') }}_{{ ansible_system }}_toolboxes.yml"

- name: "Vérification de l'existence du fichier de tâche toolboxes"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ toolboxes_task_file }}"
  register: toolboxes_task_exists
  delegate_to: localhost

- name: "Exécution de la tâche toolboxes spécifique à l'OS"
  ansible.builtin.include_tasks: "{{ toolboxes_task_file }}"
  when: toolboxes_task_exists.stat.exists

- name: "Fallback - Tâche générique toolboxes si spécifique introuvable"
  ansible.builtin.include_tasks: "verify_generic_toolboxes.yml"
  when: not toolboxes_task_exists.stat.exists

- name: "Affichage du statut d'exécution toolboxes"
  ansible.builtin.debug:
    msg:
      - "Rôle toolboxes exécuté"
      - "Fichier: {{ toolboxes_task_file if toolboxes_task_exists.stat.exists else 'verify_generic_toolboxes.yml' }}"
      - "Opération: {{ toolboxes_operation | default('verify') }}"
