---

- set_fact:
    toolboxes_component: "{{ role_name.split('_')[-1] }}"
    toolboxes_role_name: "{{ role_name }}"

- name: include tasks operation
  block:
    - name: Check if task file exists
      local_action: stat path={{ role_path }}/tasks/{{ toolboxes_task_file_name }}
      become: no
      register: statResult
      failed_when: statResult.stat.exists == false

    - name: Include tasks if file exists
      include_tasks: "{{ toolboxes_task_file_name }}"
      when: statResult.stat.exists

  rescue:
    - name: Set result as failed operation
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "info"
        set_results_item: ""
        set_results_component: "{{ toolboxes_component }}"
        set_results_operation: "{{ toolboxes_operation }}"
        set_results_role_name: "{{ toolboxes_role_name }}"
        set_results_status: "KO"
        set_results_value: >
          {% if statResult.stat.exists == false %}
            task {{ toolboxes_task_file_name }} does not exist
          {% else %}
            task execution error
          {% endif %}
