---
- name: "Initialisation du rôle maître ips_toolbox_toolboxes"
  set_fact:
    toolboxes_component: "toolboxes"
    toolboxes_role_name: "ips_toolbox_toolboxes"

- name: "Construction du nom de fichier de tâche toolboxes selon l'OS"
  set_fact:
    toolboxes_task_file: "{{ toolboxes_operation | default('verify') }}_{{ ansible_system }}_toolboxes.yml"

- name: "Vérification de l'existence du fichier de tâche toolboxes"
  stat:
    path: "{{ role_path }}/tasks/{{ toolboxes_task_file }}"
  register: toolboxes_task_exists
  delegate_to: localhost
  failed_when: false

- name: "Exécution de la tâche toolboxes spécifique à l'OS"
  include_tasks: "{{ toolboxes_task_file }}"
  when: toolboxes_task_exists.stat.exists
  ignore_errors: true

- name: "Fallback - Tâche générique toolboxes si spécifique introuvable"
  include_tasks: "verify_generic_toolboxes.yml"
  when: not toolboxes_task_exists.stat.exists
  ignore_errors: true

- name: "Affichage du statut d'exécution toolboxes"
  debug:
    msg:
      - "Rôle toolboxes maître exécuté"
      - "Fichier: {{ toolboxes_task_file if toolboxes_task_exists.stat.exists else 'verify_generic_toolboxes.yml' }}"
      - "OS: {{ ansible_system }}"
      - "Opération: {{ toolboxes_operation | default('verify') }}"
