---

- name: check available toolbox versions
  script: check_kmo_AIX.ksh {{ toolboxes_repo_url }}
  register: checkkmoscript
  changed_when: false
  failed_when: false

- set_fact:
     state_value_json: ""

- set_fact:
     state_value_json: "{{ checkkmoscript.stdout_lines | select('match','.*ERROR :.*') | list }}"

- name: set results output
  include_role:
    name: ips_toolbox_set_results
  vars:
     set_results_item: ""
     set_results_component: "{{ toolboxes_component }}"
     set_results_operation: "{{ toolboxes_operation }}"
     set_results_role_name: "{{ toolboxes_role_name }}"
     set_results_result_name: "{{ toolboxes_result_name }}"
     set_results_state: "info"
     set_results_status: "{% if checkkmoscript.rc == 0 %}\

             OK\

          {% else %}\

             KO\

       {% endif %}"
     set_results_value: "{% if checkkmoscript.rc == 0 %}\

             {{ checkkmoscript.stdout_lines | select('match', '.*available.*') | list }}\

           {% else %}\

             {{ state_value_json }}\

           {% endif %}"
 


n