# main_playbook_horsprod.yml
---
- name: "SHA Application Environment Builder - HORS-PRODUCTION"
  hosts: "{{ Hostname | default('all') }}"
  gather_facts: true
  become: true
  serial: 1

  vars:
    environment_type: "HORSPROD"
    code_ap: "{{ CodeAP }}"
    code5car: "{{ code5car }}"
    hostname_target: "{{ Hostname }}"
    execution_timestamp: "{{ ansible_date_time.iso8601 }}"
    execution_id: "{{ ansible_date_time.epoch }}"
    report_dir: "/tmp/ansible_reports"
    validation_level: "low"
    allow_testing_features: true
    allow_experimental_features: true
    skip_backup: false

  pre_tasks:
    - name: "[HORSPROD] Validation des variables obligatoires"
      ansible.builtin.assert:
        that:
          - CodeAP is defined and CodeAP != ""
          - code5car is defined and code5car != ""
          - Hostname is defined and Hostname != ""
        fail_msg: "Les variables CodeAP, code5car et Hostname sont obligatoires"
    - name: "[HORSPROD] Création du répertoire de rapport"
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
    - name: "[HORSPROD] Initialisation du rapport d'exécution"
      ansible.builtin.set_fact:
        execution_report:
          environment: "{{ environment_type }}"
          hostname: "{{ hostname_target }}"
          code_ap: "{{ code_ap }}"
          code5car: "{{ code5car }}"
          execution_id: "{{ execution_id }}"
          start_time: "{{ execution_timestamp }}"
          detected_os: ""
          detected_middleware: []
          filesystem_changes: []
          installed_packages: []
          created_users: []
          modified_configs: []
          services_status: []
          experimental_features: []
          errors: []
          warnings: []

  tasks:
    - name: "Bloc principal avec gestion d'échec"
      block:
        # ===== PHASES identiques, mode permissif, + dev/expérimental =====
        - name: "[HORSPROD] Détection de l'OS et collecte des faits système"
          ansible.builtin.include_role:
            name: app_environment_builder
            tasks_from: detect_os
        - name: "[HORSPROD] Détection du middleware installé"
          ansible.builtin.include_role:
            name: app_environment_builder
            tasks_from: detect_middleware
          vars:
            detection_mode: "comprehensive"
        - name: "[HORSPROD] Mise à jour du rapport avec les détections"
          ansible.builtin.set_fact:
            execution_report: "{{ execution_report | combine({
              'detected_os': detected_os_info,
              'detected_middleware': detected_middleware_list
            }) }}"
        - name: "[HORSPROD] Création du point de rollback (optionnel)"
          ansible.builtin.include_role:
            name: backup_manager
            tasks_from: create_rollback_point
          vars:
            backup_type: "pre_deployment_dev"
            backup_retention: "3d"
          when: not skip_backup
        - name: "[HORSPROD] Vérification de la conformité du serveur (niveau bas)"
          ansible.builtin.include_role:
            name: ips_toolbox_system
          vars:
            system_operation: "check_conformity"
            validation_level: "{{ validation_level }}"
            allow_warnings: true
        - name: "[HORSPROD] Création de l'arborescence applicative"
          ansible.builtin.include_role:
            name: app_environment_builder
            tasks_from: create_app_structure
          vars:
            target_codeap: "{{ code_ap }}"
            target_code5car: "{{ code5car }}"
            environment_type: "HORSPROD"
            enable_dev_features: true
        - name: "[HORSPROD] Configurations spécifiques OS"
          block:
            - name: "AIX"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: aix_setup
              vars:
                environment_type: "HORSPROD"
                enable_debug_tools: true
              when: detected_os_info.family == "AIX"
            - name: "RHEL"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: rhel_setup
              vars:
                environment_type: "HORSPROD"
                enable_debug_tools: true
                install_dev_packages: true
              when: detected_os_info.family == "RedHat"
            - name: "Windows"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: windows_setup
              vars:
                environment_type: "HORSPROD"
                enable_debug_tools: true
              when: detected_os_info.family == "Windows"
        - name: "[HORSPROD] Configuration des middlewares avec options dev/expérimental"
          block:
            - name: "WebSphere WAS ND"
              ansible.builtin.include_role:
                name: ips_toolbox_wasnd
              vars:
                was_environment: "HORSPROD"
                enable_debug_mode: true
                enable_development_mode: true
                log_level: "FINEST"
              when: "'WebSphere_WAS_ND' in detected_middleware_list"
            - name: "WebSphere WAS Base"
              ansible.builtin.include_role:
                name: ips_toolbox_wasbase
              vars:
                was_environment: "HORSPROD"
                enable_debug_mode: true
                enable_development_mode: true
                log_level: "FINEST"
              when: "'WebSphere_WAS_Base' in detected_middleware_list"
            - name: "Liberty Core"
              ansible.builtin.include_role:
                name: ips_toolbox_libertycore
              vars:
                liberty_environment: "HORSPROD"
                enable_developer_features: true
              when: "'Liberty_Core' in detected_middleware_list"
            - name: "Liberty Base"
              ansible.builtin.include_role:
                name: ips_toolbox_libertybase
              vars:
                liberty_environment: "HORSPROD"
                enable_developer_features: true
              when: "'Liberty_Base' in detected_middleware_list"
            - name: "IHS"
              ansible.builtin.include_role:
                name: ips_toolbox_webserver
              vars:
                ihs_environment: "HORSPROD"
                enable_debug_mode: true
              when: "'IHS' in detected_middleware_list"
            - name: "Oracle"
              ansible.builtin.include_role:
                name: ips_toolbox_oracle
              vars:
                oracle_environment: "HORSPROD"
                enable_archive_log: false
                enable_debug_mode: true
              when: "'Oracle' in detected_middleware_list"
            - name: "SQL Server"
              ansible.builtin.include_role:
                name: ips_toolbox_sqlserver
              vars:
                sqlserver_environment: "HORSPROD"
                enable_debug_mode: true
              when: "'SQLServer' in detected_middleware_list"
            - name: "MQ Series"
              ansible.builtin.include_role:
                name: ips_toolbox_mq
              vars:
                mq_environment: "HORSPROD"
                enable_debug_mode: true
              when: "'MQSeries' in detected_middleware_list"
            - name: "CFT"
              ansible.builtin.include_role:
                name: ips_toolbox_cft
              vars:
                cft_environment: "HORSPROD"
              when: "'CFT' in detected_middleware_list"
        - name: "[HORSPROD] Configuration des services système (dev)"
          block:
            - name: "Toolbox système"
              ansible.builtin.include_role:
                name: ips_toolbox_toolboxes
              vars:
                toolbox_environment: "HORSPROD"
                enable_all_modules: true
            - name: "Sauvegarde TSM"
              ansible.builtin.include_role:
                name: ips_toolbox_backup
              vars:
                backup_operation: "configure_appli_backup"
                backup_codeap: "{{ code_ap }}"
                backup_code5car: "{{ code5car }}"
                backup_environment: "HORSPROD"
                backup_frequency: "manual"
                backup_retention: "3d"
            - name: "Illumio"
              ansible.builtin.include_role:
                name: ips_toolbox_illumio
              vars:
                illumio_environment: "HORSPROD"
                illumio_mode: "test"
                enable_learning_mode: true
              when: "'Illumio' in detected_middleware_list"
            - name: "Services applicatifs"
              ansible.builtin.include_role:
                name: ips_toolbox_services
              vars:
                services_environment: "HORSPROD"
                enable_debug_services: true
        - name: "[HORSPROD] Vérifications et tests étendus"
          block:
            - name: "Arborescence"
              ansible.builtin.stat:
                path: "/applis/{{ code_ap }}-{{ code5car }}"
              register: appli_dir_check
            - name: "Filesystems"
              ansible.builtin.shell: |
                df -h | grep "/applis/{{ code_ap }}-{{ code5car }}"
              register: filesystem_check
              failed_when: false
              changed_when: false
            - name: "Scripts applicatifs"
              ansible.builtin.stat:
                path: "/etc/local/app_{{ code5car }}_status"
              register: appli_scripts_check
            - name: "Tests de validation développement"
              ansible.builtin.shell: |
                echo "Tests HORSPROD - Validation complète"
                ls -la "/applis/{{ code_ap }}-{{ code5car }}"
                echo "Vérification permissions dev"
                find "/applis/{{ code_ap }}-{{ code5car }}" -type d -exec ls -ld {} \;
              register: horsprod_extended_tests
              failed_when: false
              changed_when: false
            - name: "Tests fonctionnalités expérimentales"
              ansible.builtin.shell: |
                echo "Test fonctionnalités expérimentales activées"
                echo "Environnement: {{ environment_type }}"
                echo "Code5car: {{ code5car }}"
              register: experimental_tests
              when: allow_experimental_features
              failed_when: false
              changed_when: false
        - name: "[HORSPROD] Rapport final étendu"
          block:
            - name: "Collecte des informations finales"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: collect_facts
              vars:
                environment_type: "HORSPROD"
            - name: "Génération du rapport JSON"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_json
              vars:
                environment_type: "HORSPROD"
            - name: "Génération du résumé stdout"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_stdout
              vars:
                environment_type: "HORSPROD"
            - name: "Affichage du résumé d'exécution étendu"
              ansible.builtin.debug:
                msg: |
                  =========================================================
                  RÉSUMÉ D'EXÉCUTION - ENVIRONNEMENT HORS-PRODUCTION
                  =========================================================
                  Serveur cible      : {{ hostname_target }}
                  Code AP            : {{ code_ap }}
                  Code5car           : {{ code5car }}
                  OS détecté         : {{ detected_os_info.distribution | default('N/A') }} {{ detected_os_info.version | default('') }}
                  Middleware         : {{ detected_middleware_list | join(', ') if detected_middleware_list else 'Aucun' }}
                  Statut             : {{ 'SUCCÈS' if deployment_success | default(true) else 'ÉCHEC' }}
                  Rapport JSON       : {{ report_dir }}/execution_report_{{ execution_id }}.json
                  =========================================================
      rescue:
        - name: "Gestion des erreurs et rollback HORS-PROD"
          block:
            - name: "Enregistrement de l'erreur"
              ansible.builtin.set_fact:
                execution_report: "{{ execution_report | combine({
                  'errors': execution_report.errors + [ansible_failed_result.msg | default('Erreur inconnue')],
                  'success': false,
                  'end_time': ansible_date_time.iso8601,
                  'error_tolerance_mode': true
                }) }}"
            - name: "Génération du rapport d'erreur"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_json
              vars:
                environment_type: "HORSPROD"
            - name: "Affichage des erreurs (mode dev)"
              ansible.builtin.debug:
                msg: |
                  =========================================================
                  ERREUR - ENVIRONNEMENT HORS-PRODUCTION
                  =========================================================
                  Une erreur s'est produite lors du déploiement.
                  En mode développement, certaines erreurs peuvent être tolérées.
                  Consulter le rapport JSON pour analyser l'erreur.
                  Rapport : {{ report_dir }}/execution_report_{{ execution_id }}.json
                  =========================================================
            - name: "Échec du playbook HORS-PROD"
              ansible.builtin.fail:
                msg: "Déploiement échoué en environnement HORS-PRODUCTION - Voir rapport pour détails"
