---
- name: "Application Environment Builder"
  hosts: "{{ Hostname | default('all') }}"
  gather_facts: true
  become: true
  serial: 1

  vars:
    # Variables statiques
    environment_type: "HORSPROD"
    code_ap: "{{ CodeAP }}"
    code5car: "{{ code5car }}"
    hostname_target: "{{ Hostname }}"
    execution_timestamp: "{{ ansible_date_time.iso8601 }}"
    execution_id: "{{ ansible_date_time.epoch }}"
    report_dir: "/tmp/ansible_reports"

  pre_tasks:
    - name: "[HORSPROD] Validation des variables Survey AAP2"
      ansible.builtin.assert:
        that:
          - CodeAP is defined and CodeAP != ""
          - code5car is defined and code5car != ""
          - Hostname is defined and Hostname != ""
          - CodeAP | regex_search('^[0-9]{5}$')
          - code5car | regex_search('^[A-Za-z0-9]{5}$')
        fail_msg: "Variables Survey AAP2 invalides. CodeAP (5 chiffres) et code5car (5 alphanum) requis"

    - name: "[HORSPROD] Création du répertoire de rapports"
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'

    - name: "[HORSPROD] Initialisation du rapport d'exécution"
      ansible.builtin.set_fact:
        execution_report:
          execution_metadata:
            environment: "{{ environment_type }}"
            hostname: "{{ hostname_target }}"
            code_ap: "{{ code_ap }}"
            code5car: "{{ code5car }}"
            execution_id: "{{ execution_id }}"
            start_time: "{{ execution_timestamp }}"
          system_detection:
            detected_os: {}
            detected_middleware: []
            detected_services: []
            middleware_details: {}
            services_details: {}
          infrastructure_changes:
            filesystem_changes: []
          compliance_validation:
            bp2i_compliance: {}
          execution_results:
            errors: []

  tasks:
    - name: "Phase 1 – Détection et audit système"
      block:
        - name: "Détection OS"
          ansible.builtin.include_role:
            name: app_environment_builder
            tasks_from: detect_os
          tags: [detection, os]

        - name: "Détection middleware/services"
          ansible.builtin.include_role:
            name: app_environment_builder
            tasks_from: detect_middleware
          tags: [detection, middleware]
        
        - name: "Audit toolbox"
          ansible.builtin.include_role:
            name: ips_toolbox_launcher
          tags: [audit, toolbox]

      rescue:
        - name: "[HORSPROD] Gestion des erreurs – Phase 1"
          ansible.builtin.debug:
            msg: "Erreur détection/ audit tolérée en mode HORS-PRODUCTION"

    - name: "Phase 2 – Sauvegarde pré-déploiement"
      block:
        - name: "Sauvegarde incrémentale"
          ansible.builtin.include_role:
            name: ips_toolbox_backup
            vars:
              backup_operation: "run_incr"

      rescue:
        - name: "[HORSPROD] Sauvegarde échouée tolérée"
          ansible.builtin.debug:
            msg: "Erreur backup tolérée"

    - name: "Phase 3 – Vérifications système"
      block:
        - name: "Statut système"
          ansible.builtin.include_role:
            name: ips_toolbox_system
            vars:
              system_operation: "status"

        - name: "Uptime < 90j"
          ansible.builtin.include_role:
            name: ips_toolbox_system
            vars:
              system_operation: "uptime"

    - name: "Phase 4 – Arborescence applicative"
      block:
        - name: "Création /applis/{{ code_ap }}-{{ code5car }}"
          ansible.builtin.include_role:
            name: ips_toolbox_system
            vars:
              system_operation: "create-directory"
              system_codeAP: "{{ code_ap }}"
              system_code5car: "{{ code5car }}"

    - name: "Phase 5 – Configuration middlewares"
      block:
        - name: "WebSphere WAS ND"
          ansible.builtin.include_role:
            name: ips_toolbox_wasnd
          when: "'WebSphere_WAS_ND' in detected_middleware_list"
        
        - name: "Oracle Database"
          ansible.builtin.include_role:
            name: ips_toolbox_oracle
          when: "'Oracle' in detected_middleware_list"

    - name: "Phase 6 – Configuration services"
      block:
        - name: "Illumio VEN"
          ansible.builtin.include_role:
            name: ips_toolbox_illumio

        - name: "TSM Agent"
          ansible.builtin.include_role:
            name: ips_toolbox_tsm

    - name: "Phase 7 – Vérifications post-déploiement"
      block:
        - name: "Vérification /applis"
          ansible.builtin.stat:
            path: "/applis/{{ code_ap }}-{{ code5car }}"
          register: stat_applis

        - name: "Vérification /apps"
          ansible.builtin.stat:
            path: "/apps"
          register: stat_apps

        - name: "Rotation logs"
          ansible.builtin.systemd:
            name: purge_logs.timer
            state: started

    - name: "Phase 8 – Rapport final"
      block:
        - name: "Génération rapport JSON"
          ansible.builtin.include_role:
            name: report_generator
            tasks_from: generate_json

        - name: "Affichage résumé"
          ansible.builtin.debug:
            msg: "Rapport JSON généré"

      rescue:
        - name: "[HORSPROD] Rapport échoué toléré"
          ansible.builtin.debug:
            msg: "Erreur rapport tolérée"
