# main_playbook_horsprod.yml
# Main playbook pour environnement HORS-PRODUCTION (bloc rescue corrigé)
---
- name: "SHA Application Environment Builder - HORS-PRODUCTION"
  hosts: "{{ hostname | default('all') }}"
  gather_facts: true
  become: true
  serial: 1

  vars:
    environment_type: "HORSPROD"
    code_ap: "{{ CodeAP }}"
    code5car: "{{ code5car }}"
    hostname_target: "{{ Hostname }}"
    execution_timestamp: "{{ ansible_date_time.iso8601 }}"
    execution_id: "{{ ansible_date_time.epoch }}"
    report_dir: "/tmp/ansible_reports"
    validation_level: "low"
    allow_testing_features: true
    allow_experimental_features: true
    skip_backup: false

  pre_tasks:
    - name: "[HORSPROD] Validation des variables obligatoires"
      ansible.builtin.assert:
        that:
          - CodeAP is defined and CodeAP != ""
          - code5car is defined and code5car != ""
          - Hostname is defined and Hostname != ""
        fail_msg: "Les variables CodeAP, code5car et Hostname sont obligatoires"
      tags: [validation]

    - name: "[HORSPROD] Création du répertoire de rapport"
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
      tags: [setup]

    - name: "[HORSPROD] Initialisation du rapport d'exécution"
      ansible.builtin.set_fact:
        execution_report:
          environment: "{{ environment_type }}"
          hostname: "{{ hostname_target }}"
          code_ap: "{{ code_ap }}"
          code5car: "{{ code5car }}"
          execution_id: "{{ execution_id }}"
          start_time: "{{ execution_timestamp }}"
          detected_os: ""
          detected_middleware: []
          filesystem_changes: []
          installed_packages: []
          created_users: []
          modified_configs: []
          services_status: []
          experimental_features: []
          errors: []
          warnings: []
      tags: [setup]

  tasks:
    - name: "[HORSPROD] Pipeline principal avec gestion d'échec"
      block:
        # Toutes les phases principales (adaptées du code initial : détection, sauvegarde optionnelle, création env, middlewares, post, rapport)
        # Copiez/adaptez ici votre logique d'enchaînement de tâches
        - name: "[HORSPROD] ... (Votre pipeline complet ici, même modèle que PROD, logic spécifique horsprod)"

      rescue:
        - name: "[HORSPROD] Gestion des erreurs (mode tolérant)"
          block:
            - name: "[HORSPROD] Enregistrement de l'erreur"
              ansible.builtin.set_fact:
                execution_report: "{{ execution_report | combine({
                  'errors': execution_report.errors + [ansible_failed_result.msg | default('Erreur inconnue')],
                  'success': false,
                  'end_time': ansible_date_time.iso8601,
                  'error_tolerance_mode': true
                }) }}"

            - name: "[HORSPROD] Génération du rapport d'erreur"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_json

            - name: "[HORSPROD] Affichage de l'erreur (mode dev)"
              ansible.builtin.debug:
                msg: |
                  =========================================================
                  ERREUR - ENVIRONNEMENT HORS-PRODUCTION
                  =========================================================
                  Une erreur s'est produite lors du déploiement.
                  En mode développement, certaines erreurs peuvent être tolérées.
                  Consulter le rapport JSON pour analyser l'erreur.
                  Rapport : {{ report_dir }}/execution_report_{{ execution_id }}.json
                  =========================================================

            - name: "[HORSPROD] Décision sur l'échec (tolérance en dev)"
              ansible.builtin.fail:
                msg: "Déploiement échoué en environnement HORS-PRODUCTION - Voir rapport pour détails"
              when: not (ansible_failed_result.msg is search('warning') or ansible_failed_result.msg is search('non-critical'))
