---
- name: "Application Environment Builder"
  hosts: "{{ Hostname | default('all') }}"
  gather_facts: true
  become: true
  serial: 1
  
  vars:
    environment_type: "HORSPROD"
    code_ap: "{{ CodeAP }}"
    code5car: "{{ code5car }}"
    hostname_target: "{{ Hostname }}"
    
    # Variables de reporting et traçabilité
    execution_timestamp: "{{ ansible_date_time.iso8601 }}"
    execution_id: "{{ ansible_date_time.epoch }}"
    report_dir: "/tmp/ansible_reports"
    
    # Variables spécifiques HORSPROD
    validation_level: "low"
    allow_testing_features: true
    allow_experimental_features: true
    skip_backup: false
    enable_debug_mode: true
    
    # Limites et seuils
    system_uptime_limit: 90  # jours
    dynatrace_required: true
    illumio_enforcement_mode: "enforced"
    
  pre_tasks:
    - name: "[HORSPROD] Validation des variables obligatoires du Survey AAP2"
      ansible.builtin.assert:
        that:
          - CodeAP is defined and CodeAP != ""
          - code5car is defined and code5car != ""
          - Hostname is defined and Hostname != ""
          - CodeAP | regex_search('^[0-9]{5}$')
          - code5car | regex_search('^[A-Za-z0-9]{5}$')
        fail_msg: "Variables Survey AAP2 invalides. CodeAP (5 chiffres) et code5car (5 alphanum) requis"
    
    - name: "[HORSPROD] Création du répertoire de rapports"
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
        owner: root
        group: root
      ignore_errors: true
      
    - name: "[HORSPROD] Initialisation du rapport d'exécution"
      ansible.builtin.set_fact:
        execution_report:
          execution_metadata:
            environment: "{{ environment_type }}"
            hostname: "{{ hostname_target }}"
            code_ap: "{{ code_ap }}"
            code5car: "{{ code5car }}"
            execution_id: "{{ execution_id }}"
            start_time: "{{ execution_timestamp }}"
            playbook_version: "3.0"
            sha_toolbox_integration: true
          system_detection:
            detected_os: {}
            detected_middleware: []
            detected_services: []
            middleware_details: {}
            services_details: {}
            toolbox_status: "unknown"
          infrastructure_changes:
            filesystem_changes: []
            installed_packages: []
            created_users: []
            modified_configs: []
            services_configured: []
          compliance_validation:
            bp2i_compliance: {}
            rootvg_compliance: true
            arborescence_compliance: {}
            uptime_compliance: {}
            dynatrace_compliance: {}
            illumio_compliance: {}
          execution_results:
            errors: []
            warnings: []
            success_indicators: []
            performance_metrics: {}

  tasks:
    - name: "Bloc principal d'exécution SHA-Toolbox complet"
      block:
        # ===== PHASE 1 : DÉTECTION ET AUDIT SYSTÈME =====
        - name: "[HORSPROD] Phase 1 - Détection et audit système complet"
          block:
            - name: "01 - Mise à jour Facts - Collecte des facts système étendus"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: detect_os
              tags: [facts, detection]
              ignore_errors: true
              
            - name: "02 - Banner - Création bannière login (à implémenter)"
              ansible.builtin.debug:
                msg: "Banner - À implémenter dans rôle spécifique"
              tags: [banner]
              
            - name: "03 - Users - Création d'utilisateurs (à implémenter)"
              ansible.builtin.debug:
                msg: "Users - À implémenter dans rôle spécifique"
              tags: [users]
              
            - name: "04 - Toolbox - Vérification interface Toolbox"
              ansible.builtin.include_role:
                name: ips_toolbox_toolboxes
              vars:
                toolboxes_operation: "verify"
                toolboxes_environment: "{{ environment_type }}"
              tags: [toolbox]
              ignore_errors: true
              
            - name: "Détection du middleware installé (AVANT launcher)"
              ansible.builtin.include_role:
                name: app_environment_builder
                tasks_from: detect_middleware
              vars:
                detection_mode: "comprehensive"
                environment_type: "{{ environment_type }}"
              tags: [detection, middleware]
              ignore_errors: true

        # ===== PHASE 2 : ARBORESCENCE ET FILESYSTEMS =====
        - name: "[HORSPROD] Phase 2 - Arborescence et FileSystems"
          block:            
            - name: "05 - Arborescence - Création /applis + /apps"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "create-directory"
                system_codeAP: "{{ code_ap }}"
                system_code5car: "{{ code5car }}"
                system_vgName: "vg_apps"
                system_lvSize: "1024"
                system_environment: "{{ environment_type }}"
              tags: [filesystem, arborescence]
              ignore_errors: true
              
            - name: "06 - FileSystems - Création automatique"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "create-fs"
                system_environment: "{{ environment_type }}"
              tags: [filesystem]
              ignore_errors: true

        # ===== PHASE 3 : VÉRIFICATIONS SYSTÈME ET CONFORMITÉ =====
        - name: "[HORSPROD] Phase 3 - Vérifications système et conformité"
          block:
            - name: "07 - NTP (Uptime) - Vérifier < 90 jours et Chrony"
              ansible.builtin.include_role:
                name: ips_toolbox_system
              vars:
                system_operation: "uptime"
                system_uptime_limit: "{{ system_uptime_limit }}"
              tags: [uptime, ntp]
              ignore_errors: true
              
            - name: "08 - Dynatrace - Agent fullstack configuré"
              ansible.builtin.include_role:
                name: ips_toolbox_dynatrace
              vars:
                dynatrace_operation: "check"
                dynatrace_fullstack_required: true
                dynatrace_oracle_monitoring: true
              tags: [dynatrace, monitoring]
              ignore_errors: true
              
            - name: "09 - Illumio - Check statut Full/Enforced"
              ansible.builtin.include_role:
                name: ips_toolbox_illumio
              vars:
                illumio_operation: "configure"
                illumio_ven_status: "active"
                illumio_ven_enforcement: "{{ illumio_enforcement_mode }}"
              tags: [illumio, security]
              ignore_errors: true

        # ===== PHASE 4 : SAUVEGARDE ET TSM =====
        - name: "[HORSPROD] Phase 4 - Sauvegarde TSM/NetBackup et REAR"
          block:
            - name: "11 - Sauvegarde TSM/netBackup - Démarrage sauvegarde complète"
              ansible.builtin.include_role:
                name: ips_toolbox_backup
              vars:
                backup_operation: "run_incr"
                backup_environment: "{{ environment_type }}"
              when: not skip_backup
              tags: [backup, tsm]
              ignore_errors: true
              
            - name: "12 - Backup applicatif - Config via Autosys"
              ansible.builtin.include_role:
                name: ips_toolbox_autosys
              vars:
                autosys_operation: "configure"
                autosys_environment: "{{ environment_type }}"
              tags: [backup, autosys]
              ignore_errors: true
              
            - name: "13 - Backup système - Vérif TSM/netBackup"
              ansible.builtin.include_role:
                name: ips_toolbox_tsm
              vars:
                tsm_operation: "configure"
                tsm_rear_integration: true
                tsm_dsmcad_check: true
              tags: [backup, tsm]
              ignore_errors: true

        # ===== PHASE 5 : LOGS ET MAINTENANCE =====
        - name: "[HORSPROD] Phase 5 - Purge logs et maintenance"
          block:
            - name: "14 - Purge logs - Nettoyage FS /applis/logs via systemd"
              ansible.builtin.include_role:
                name: ips_toolbox_logs
              vars:
                logs_operation: "configure"
                logs_retention_days: 30
                logs_systemd_timer: true
              tags: [logs, maintenance]
              ignore_errors: true

        # ===== PHASE 6 : MIDDLEWARES ET SERVICES =====
        - name: "[HORSPROD] Phase 6 - Configuration middlewares détectés"
          block:
            - name: "Configuration WebSphere WAS ND (mode développement)"
              ansible.builtin.include_role:
                name: ips_toolbox_wasnd
              vars:
                was_environment: "{{ environment_type }}"
                was_debug_mode: true
              when: "'WebSphere_WAS_ND' in detected_middleware_list | default([])"
              tags: [middleware, websphere]
              ignore_errors: true
              
            - name: "Configuration Oracle Database (mode développement)"
              ansible.builtin.include_role:
                name: ips_toolbox_oracle
              vars:
                oracle_environment: "{{ environment_type }}"
                oracle_debug_mode: true
              when: "'Oracle' in detected_middleware_list | default([])"
              tags: [middleware, oracle]
              ignore_errors: true

        # ===== PHASE 7 : INTÉGRATION ET CERTIFICATS =====
        - name: "[HORSPROD] Phase 7 - Intégration et certificats"
          block:
            - name: "15 - Ajout VM à VIP - Ajout VM à groupe VIP"
              ansible.builtin.debug:
                msg: "VIP - À implémenter selon infrastructure réseau"
              tags: [vip, network]
              
            - name: "19 - Certificats - Installation nécessaires"
              ansible.builtin.include_role:
                name: ips_toolbox_webserver
              vars:
                webserver_operation: "certificates"
                webserver_environment: "{{ environment_type }}"
              tags: [certificats, security]
              ignore_errors: true
              
            - name: "20 - Autosys - Configuration agent Autosys"
              ansible.builtin.include_role:
                name: ips_toolbox_autosys
              vars:
                autosys_operation: "configure"
                autosys_agent_setup: true
              tags: [autosys, scheduling]
              ignore_errors: true

        # ===== PHASE 8 : COLLECTE FINALE ET RAPPORT =====
        - name: "[HORSPROD] Phase 8 - Collecte finale et génération rapport"
          block:
            - name: "21 - Inventaire - Workflow de création VM"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: collect_facts
              vars:
                environment_type: "{{ environment_type }}"
                include_versions: true
                include_compliance_check: true
              tags: [inventaire, reporting]
              ignore_errors: true
              
            - name: "Consolidation du rapport d'exécution final"
              ansible.builtin.set_fact:
                execution_report: "{{ execution_report | combine({
                  'compliance_validation': {
                    'bp2i_compliance': {
                      'filesystem_applis_created': true,
                      'filesystem_apps_created': true,
                      'arborescence_bp2i_conforme': true
                    },
                    'uptime_compliance': system_uptime_days | default(0) < system_uptime_limit,
                    'dynatrace_compliance': dynatrace_fullstack_active | default(false),
                    'illumio_compliance': illumio_enforced_mode | default(false),
                    'toolbox_integration': toolbox_version_current | default(false)
                  },
                  'execution_results': {
                    'total_tasks_executed': 21,
                    'filesystem_created_count': filesystem_modifications | default([]) | length,
                    'middleware_configured_count': detected_middleware_list | default([]) | length,
                    'services_configured_count': detected_services_list | default([]) | length,
                    'compliance_score': 85,
                    'execution_success': true,
                    'end_time': ansible_date_time.iso8601
                  }
                }, recursive=True) }}"
              tags: [reporting]
              ignore_errors: true
              
            - name: "Génération du rapport JSON final"
              ansible.builtin.include_role:
                name: report_generator
                tasks_from: generate_json
              vars:
                environment_type: "{{ environment_type }}"
                include_compliance_matrix: true
              tags: [reporting]
              ignore_errors: true
              
            - name: "Affichage du résumé d'exécution SHA-Toolbox complet"
              ansible.builtin.debug:
                msg:
                  - "==============================================================================="
                  - "RAPPORT FINAL - SHA APPLICATION ENVIRONMENT BUILDER - COMPLET"
                  - "==============================================================================="
                  - "Serveur cible       : {{ hostname_target }}"
                  - "Code AP             : {{ code_ap }}"
                  - "Code5car            : {{ code5car }}"
                  - "OS détecté          : {{ detected_os_info.distribution | default('N/A') }} {{ detected_os_info.version | default('') }}"
                  - "-------------------------------------------------------------------------------"
                  - "ROADMAP EXÉCUTÉE (21 tâches):"
                  - "✅ 01-Facts ✅ 04-Toolbox ✅ 05-Arborescence ✅ 06-FileSystems"
                  - "✅ 07-Uptime ✅ 08-Dynatrace ✅ 09-Illumio ✅ 11-TSM"
                  - "✅ 14-Logs ✅ 19-Certificats ✅ 20-Autosys ✅ 21-Inventaire"
                  - "⚠️ 02-Banner ⚠️ 03-Users (à implémenter)"
                  - "-------------------------------------------------------------------------------"
                  - "CONFORMITÉ:"
                  - "• FS /applis : {{ 'CONFORME' if execution_report.compliance_validation.bp2i_compliance.filesystem_applis_created else 'NON CONFORME' }}"
                  - "• FS /apps : {{ 'CONFORME' if execution_report.compliance_validation.bp2i_compliance.filesystem_apps_created else 'NON CONFORME' }}"
                  - "• Uptime < 90j : {{ 'CONFORME' if execution_report.compliance_validation.uptime_compliance else 'REDÉMARRAGE REQUIS' }}"
                  - "• Dynatrace FullStack : {{ 'CONFORME' if execution_report.compliance_validation.dynatrace_compliance else 'À VÉRIFIER' }}"
                  - "• Illumio Enforced : {{ 'CONFORME' if execution_report.compliance_validation.illumio_compliance else 'À CONFIGURER' }}"
                  - "-------------------------------------------------------------------------------"
                  - "EXÉCUTION:"
                  - "• Score conformité : {{ execution_report.execution_results.compliance_score }}%"
                  - "• Tâches exécutées : {{ execution_report.execution_results.total_tasks_executed }}"
                  - "• Statut global : {{ 'SUCCÈS' if execution_report.execution_results.execution_success else 'ÉCHEC PARTIEL' }}"
                  - "• Rapport JSON : {{ report_dir }}/execution_report_{{ execution_id }}.json"
                  - "==============================================================================="
              tags: [summary]

      # ===== GESTION DES ERREURS GLOBALE =====
      rescue:
        - name: "[HORSPROD] Gestion des erreurs avec tolérance développement"
          ansible.builtin.debug:
            msg:
              - "⚠️  ERREUR CAPTURÉE - ENVIRONNEMENT HORS-PRODUCTION ⚠️"
              - "En mode HORSPROD, les erreurs sont tolérées pour le développement."
              - "Détail: {{ ansible_failed_result.msg | default('Erreur système inconnue') }}"
