---
collections:
  # Collection communautaire
  - name: community.general
    version: ">=8.0.0"
    source: https://galaxy.ansible.com

  # Collections de base Ansible
  - name: ansible.builtin
    version: ">=2.15.0"
    source: https://galaxy.ansible.com

  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com

  # Collection Illumio officielle
  - name: illumio.core
    version: ">=0.2.6"
    source: https://galaxy.ansible.com

  # Collections pour Windows (si nécessaire)
  - name: ansible.windows
    version: ">=2.0.0"
    source: https://galaxy.ansible.com

  # Collections pour conteneurs (si nécessaire)
  - name: containers.podman
    version: ">=1.10.0"
    source: https://galaxy.ansible.com

roles:
  # Rôles communautaires utiles
  - name: geerlingguy.java
    version: "1.9.6"
    src: https://galaxy.ansible.com

  - name: geerlingguy.elasticsearch
    version: "7.6.0"
    src: https://galaxy.ansible.com
