---
# Main tasks for ips_toolbox_tsm role

- name: Check TSM client installation
  stat:
    path: "{{ backup.tsm_client_path }}"
  register: tsm_installed

- name: Fail if TSM not installed
  fail:
    msg: "TSM client is not installed on this server"
  when: not tsm_installed.stat.exists

- name: Test TSM connection
  include_tasks: test_connection.yml
  tags:
    - test
    - connection

- name: Query backup files
  include_tasks: query_files.yml
  when: query_files | default(false) | bool
  tags:
    - query
    - files

- name: Restore files
  include_tasks: restore_files.yml
  when: restore_action | default(false) | bool
  tags:
    - restore

- name: View policies
  include_tasks: view_policies.yml
  when: view_policies | default(false) | bool
  tags:
    - policies
