---
all:
  children:
    linux_servers:
      children:
        rhel_servers:
          hosts:
            # Example RHEL servers
            # rhel-dev-01:
            #   ansible_host: 10.0.1.10
            #   codeap: "12345"
            #   codescar: "APP01"
            #   environment: dev
            #   os_type: rhel8

    windows_servers:
      children:
        windows_2019:
          hosts:
            # Example Windows servers
            # win-dev-01:
            #   ansible_host: 10.0.1.20
            #   codeap: "12346"
            #   codescar: "APP02"
            #   environment: dev
            #   ansible_connection: winrm
            #   ansible_winrm_transport: ntlm

    websphere_servers:
      children:
        was_nd:
          hosts:
            # WebSphere ND servers
        was_base:
          hosts:
            # WebSphere Base servers
        liberty_core:
          hosts:
            # Liberty Core servers
        liberty_base:
          hosts:
            # Liberty Base servers

    database_servers:
      children:
        oracle_servers:
          hosts:
            # Oracle database servers
        sqlserver_servers:
          hosts:
            # SQL Server database servers

    middleware_servers:
      children:
        cft_servers:
          hosts:
            # CFT servers
        mq_servers:
          hosts:
            # MQSeries servers

  vars:
    ansible_user: ansible
    ansible_become: yes
    ansible_become_method: sudo
    environment_name: dev
