---

###
## roles Network
## task  checkport
## purpose: check port connection
##

- name: stop play when a mandatory variable is missing
  assert:
   that:
     - network_remote_hostname != ""
   msg: "at least one mandatory variable is missing beyond: network_remote_hostname"

- name: check outgoing network traffic open
  win_testPort:
    destination: "{{ network_remote_hostname }}"
    port: "{{ network_remote_port | default() }}"
  register: result
  ignore_errors: yes

- name: set result outgoing network traffic open
  include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state: "info"
    set_results_item:
      - Destination: "{{ network_remote_hostname }}"
      - Port: "{{ network_remote_port | default()  }}"
    set_results_value: "{{ result.results }}"
    set_results_component: "{{ network_component }}"
    set_results_operation: "{{ network_operation }}"
    set_results_role_name: "{{ network_role_name }}"
    set_results_result_name: "{{ network_result_name }}"
    set_results_status: "OK"
