---


- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - network_remote_hostname != ""
  msg: "Mandatory variable network_remote_hostname is missing"

- name: check port
  testPort:
    destination: "{{ network_remote_hostname }}"
    port: "{{ network_remote_port | default() }}"
  register: result

- name: set result output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: 
      - destination: "{{ network_remote_hostname }}"
      - port: "{{ network_remote_port }}"
    set_results_value: "{{ result.testPort }}"
    set_results_component: "{{ network_component }}"
    set_results_operation: "{{ network_operation }}"
    set_results_role_name: "{{ network_role_name }}"
    set_results_result_name: "{{ network_result_name }}"
    set_results_status: "OK"

