---
# Gather system information

- name: Get OS information
  setup:
    gather_subset:
      - '!all'
      - '!min'
      - hardware
      - network
      - virtual

- name: Get volume group information
  command: vgs --noheadings -o vg_name,vg_size,vg_free
  register: vg_info
  changed_when: false
  failed_when: false

- name: Get logical volume information
  command: lvs --noheadings -o lv_name,vg_name,lv_size,lv_path
  register: lv_info
  changed_when: false
  failed_when: false

- name: Get filesystem information
  command: df -h
  register: fs_info
  changed_when: false

- name: Check middleware installations
  stat:
    path: "{{ item.value }}"
  loop: "{{ middleware_paths | dict2items }}"
  register: middleware_status

- name: Display system summary
  debug:
    msg:
      - "Hostname: {{ ansible_hostname }}"
      - "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"
      - "Kernel: {{ ansible_kernel }}"
      - "Architecture: {{ ansible_architecture }}"
      - "Memory: {{ ansible_memtotal_mb }} MB"
      - "CPUs: {{ ansible_processor_vcpus }}"
      - "Volume Groups: {{ vg_info.stdout_lines | length }}"
      - "Logical Volumes: {{ lv_info.stdout_lines | length }}"

- name: Display middleware status
  debug:
    msg: "{{ item.item.key }}: {{ 'Installed' if item.stat.exists else 'Not Installed' }}"
  loop: "{{ middleware_status.results }}"
  loop_control:
    label: "{{ item.item.key }}"
