---
# Log execution to Supabase

- name: Prepare execution log data
  set_fact:
    execution_log:
      hostname: "{{ ansible_hostname }}"
      timestamp: "{{ ansible_date_time.iso8601 }}"
      role: "ips_toolbox_system"
      action: "{{ filesystem_action | default(server_action | default('info')) }}"
      environment: "{{ environment_name }}"
      user: "{{ ansible_user }}"
      status: "{{ 'success' if ansible_failed_task is not defined else 'failed' }}"
      details:
        codeap: "{{ codeap | default('N/A') }}"
        codescar: "{{ codescar | default('N/A') }}"
        filesystem_info: "{{ filesystem_info | default({}) }}"

- name: Log to Supabase via edge function
  uri:
    url: "{{ supabase_url }}/functions/v1/log-execution"
    method: POST
    headers:
      Authorization: "Bearer {{ supabase_anon_key }}"
      Content-Type: "application/json"
    body: "{{ execution_log | to_json }}"
    body_format: json
    status_code: [200, 201]
  register: supabase_log_result
  failed_when: false
  when:
    - supabase_url is defined
    - supabase_anon_key is defined
    - logging.log_to_supabase | default(true) | bool
