---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that: appli_item != ""
  msg: "appli_item variable is missing"

- name: reference status check
  ansible.builtin.find:
    paths: "/etc/local/"
    patterns: ref_status_{{ appli_item }}
  register: ref_check


- name: set results for APPLI Rhel 
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state: "info"
    set_results_item: "{{ appli_item }}"
    set_results_value: "{% if ref_check.matched > 0 %}\

                        STOPPED\

                        {% else %}\

                        STARTED\

                        {% endif %}"
    set_results_component: "{{ appli_component }}"
    set_results_operation: "{{ appli_operation }}"
    set_results_role_name: "{{ appli_role_name }}"
    set_results_result_name: "{{ appli_result_name }}"
    set_results_status: "OK"

