---

- name: Begin list CFT partners
  no_log: True

  block:

  - name: list cft
    cft:
      action: list
    register: listCFT

  - name: set facts
    ansible.builtin.set_fact:
      cft_value: "{{ listCFT.list }}"
      cft_status: "OK"

  rescue:
    - name: ansible failure
      ansible.builtin.set_fact:
        cft_value: "{{ listCFT.msg }}"
        cft_status: "KO"


  always:
  - name: set result output for CFT installation
    ansible.builtin.include_role:
      name: ips_toolbox_set_results
    vars:
      set_results_state: "info"
      set_results_item: ""
      set_results_value: "{{ cft_value }}"
      set_results_component: "{{ cft_component }}"
      set_results_operation: "{{ cft_operation }}"
      set_results_role_name: "{{ cft_role_name }}"
      set_results_result_name: "{{ cft_result_name }}"
      set_results_status: "{{ cft_status }}"

