---
# Manage Liberty Core servers

- name: Validate server action
  ansible.builtin.assert:
    that:
      - server_action in ['start', 'stop', 'status', 'list']
    fail_msg: "server_action must be 'start', 'stop', 'status', or 'list'"

- name: List Liberty servers
  shell: "{{ websphere.profile_root }}/bin/server list"
  register: liberty_servers
  changed_when: false
  when: server_action == 'list'

- name: Display Liberty servers
  ansible.builtin.debug:
    msg: "{{ liberty_servers.stdout_lines }}"
  when: server_action == 'list'

- name: Get server status
  command: "{{ websphere.profile_root }}/bin/server status {{ server_name }}"
  register: server_status
  changed_when: false
  failed_when: false
  when:
    - server_action == 'status'
    - server_name is defined

- name: Start Liberty server
  command: "{{ websphere.profile_root }}/bin/server start {{ server_name }}"
  register: server_started
  when:
    - server_action == 'start'
    - server_name is defined

- name: Stop Liberty server
  command: "{{ websphere.profile_root }}/bin/server stop {{ server_name }}"
  register: server_stopped
  when:
    - server_action == 'stop'
    - server_name is defined

- name: Display server status
  ansible.builtin.debug:
    msg: "{{ server_status.stdout_lines }}"
  when: server_status is defined
