---
- name: "Initialisation du rôle ips_toolbox_launcher"
  set_fact:
    launcher_component: "{{ role_name.split('_')[-1] }}"
    launcher_role_name: "{{ role_name }}"

- name: "Lancer la configuration WAS ND si détecté"
  include_tasks: wasnd.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'WebSphere_WAS_ND' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration WAS Base si détecté"
  include_tasks: wasebase.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'WebSphere_WAS_Base' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration Liberty Core si détecté"
  include_tasks: libertycore.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'Liberty_Core' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration Liberty Base si détecté"
  include_tasks: libertybase.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'Liberty_Base' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration IHS si détecté"
  include_tasks: webserver.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'IHS' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration Oracle si détecté"
  include_tasks: oracle.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'Oracle' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration MQ si détecté"
  include_tasks: mq.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'MQSeries' in detected_middleware_list"
  ignore_errors: true

- name: "Lancer la configuration CFT si détecté"
  include_tasks: cft.yml
  vars:
    launcher_environment: "{{ environment_type }}"
  when: "'CFT' in detected_middleware_list"
  ignore_errors: true
