---

- name: include launcher role {{ launcher_file_name }}

  block:

  - local_action: stat path={{ role_path }}/tasks/{{ launcher_file_name }}
    register: statResult
    become: no
    failed_when: statResult.stat.exists == false

  - include_tasks: "{{ launcher_file_name }}"
    when: statResult.stat.exists
    register: includetasks

  rescue:

  - name: set result failed action
    include_role:
      name: ips_toolbox_set_results
    vars:
      set_results_state: "info"
      set_results_item: ""
      set_results_component: "{{ launcher_component }}"
      set_results_operation: "{{ launcher_operation }}"
      set_results_role_name: "ips_toolboxes_{{ launcher_component }}"
      set_results_status: "KO"
      set_results_value: "\

        {% if statResult.stat.exists == false %}\

           role ips_toolbox_{{ launcher_component }} does not exist\

        {% elif includetasks.msg is defined %}\

           includetasks.msg\

        {% else %}\

           task execution error\

        {% endif %}"

