---
- name: "Vérification de l'installation du service Dynatrace OneAgent"
  ansible.builtin.shell: |
    systemctl list-units --all | grep -i oneagent && echo "SERVICE_FOUND" || echo "SERVICE_MISSING"
  register: dynatrace_service_check
  changed_when: false
  failed_when: false

- name: "Vérification du binaire OneAgent"
  ansible.builtin.stat:
    path: /opt/dynatrace/oneagent/agent/bin/oneagentctl
  register: dynatrace_binary_check

- name: "Vérification des processus OneAgent actifs"
  ansible.builtin.shell: |
    ps -ef | grep -i oneagent | grep -v grep | head -5 || echo "Aucun processus OneAgent"
  register: dynatrace_processes
  changed_when: false
  failed_when: false

- name: "Obtention du statut complet OneAgent (si installé)"
  ansible.builtin.shell: |
    if [ -f "/opt/dynatrace/oneagent/agent/bin/oneagentctl" ]; then
      echo "=== Statut complet Dynatrace OneAgent ==="
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --get-server-config 2>/dev/null || echo "Configuration serveur non disponible"
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --get-connectivity-info 2>/dev/null || echo "Info connectivité non disponible"
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --version 2>/dev/null || echo "Version non disponible"
      echo "=== Fin statut OneAgent ==="
    else
      echo "Binaire OneAgent non trouvé"
    fi
  register: dynatrace_status
  changed_when: false
  failed_when: false

- name: "Vérification du mode Full Stack"
  ansible.builtin.shell: |
    if [ -f "/opt/dynatrace/oneagent/agent/bin/oneagentctl" ]; then
      echo "=== Vérification mode Full Stack ==="
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --get-service-status 2>/dev/null | grep -E "(Infrastructure|Application|Network)" || echo "Statut services non disponible"
      echo "=== Fin vérification Full Stack ==="
    else
      echo "OneAgent non installé - vérification Full Stack impossible"
    fi
  register: dynatrace_fullstack_check
  changed_when: false
  failed_when: false

- name: "Vérification de la surveillance des bases de données Oracle"
  ansible.builtin.shell: |
    if [ -f "/opt/dynatrace/oneagent/agent/bin/oneagentctl" ]; then
      echo "=== Vérification surveillance Oracle ==="
      # Vérifier si OneAgent surveille les processus Oracle
      ps -ef | grep -E "(oracle|tnslsnr)" | grep -v grep && echo "ORACLE_PROCESSES_FOUND" || echo "ORACLE_PROCESSES_MISSING"
      
      # Vérifier la configuration du monitoring Oracle dans OneAgent
      if [ -d "/opt/dynatrace/oneagent/agent/conf" ]; then
        find /opt/dynatrace/oneagent/agent/conf -name "*.cfg" -exec grep -l -i oracle {} \; 2>/dev/null || echo "Configuration Oracle non trouvée"
      fi
      echo "=== Fin vérification Oracle ==="
    else
      echo "OneAgent non disponible pour vérifier Oracle"
    fi
  register: dynatrace_oracle_check
  changed_when: false
  failed_when: false

- name: "Configuration OneAgent en mode Full Stack si nécessaire"
  ansible.builtin.shell: |
    if [ -f "/opt/dynatrace/oneagent/agent/bin/oneagentctl" ]; then
      echo "Configuration OneAgent en mode Full Stack"
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --set-infra-only=false 2>/dev/null || echo "Configuration Full Stack échouée"
      /opt/dynatrace/oneagent/agent/bin/oneagentctl --restart-service 2>/dev/null || echo "Redémarrage service échoué"
      echo "ONEAGENT_CONFIGURED_FULLSTACK"
    else
      echo "ONEAGENT_NOT_AVAILABLE"
    fi
  register: dynatrace_configure
  when: dynatrace_binary_check.stat.exists
  changed_when: "'ONEAGENT_CONFIGURED_FULLSTACK' in dynatrace_configure.stdout"

- name: "Affichage du résumé complet Dynatrace"
  ansible.builtin.debug:
    msg:
      - "=== RÉSUMÉ DYNATRACE ONEAGENT ==="
      - "Service détecté: {{ 'Oui' if 'SERVICE_FOUND' in dynatrace_service_check.stdout else 'Non' }}"
      - "Binaire présent: {{ 'Oui' if dynatrace_binary_check.stat.exists else 'Non' }}"
      - "Processus actifs: {{ dynatrace_processes.stdout_lines | length }} processus"
      - ""
      - "STATUT ONEAGENT:"
      - "{{ dynatrace_status.stdout_lines | default(['Statut non disponible']) }}"
      - ""
      - "MODE FULL STACK:"
      - "{{ dynatrace_fullstack_check.stdout_lines | default(['Vérification Full Stack non disponible']) }}"
      - ""
      - "SURVEILLANCE ORACLE:"
      - "{{ dynatrace_oracle_check.stdout_lines | default(['Vérification Oracle non disponible']) }}"
      - "=== FIN RÉSUMÉ ==="

- name: "Enregistrement du résultat Dynatrace"
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: >-
      {% if dynatrace_binary_check.stat.exists %}
      OK
      {% else %}
      INFO
      {% endif %}
    set_results_component: "dynatrace"
    set_results_operation: "check"
    set_results_value: >-
      {% if dynatrace_binary_check.stat.exists %}
      Dynatrace OneAgent installé et configuré en mode Full Stack
      {% else %}
      Dynatrace OneAgent non installé - normal sur serveur sans Dynatrace
      {% endif %}
  ignore_errors: true
