---
- name: "Fallback Dynatrace générique"
  shell: |
    echo "=== Fallback Dynatrace ==="
    ps -ef | grep -i oneagent | grep -v grep | head -3 || echo "Aucun processus OneAgent"
    find /opt/dynatrace -maxdepth 2 -type f | head -3 || echo "/opt/dynatrace non trouvé"
    echo "=== Fin fallback Dynatrace ==="
  register: dt_generic
  changed_when: false
  failed_when: false

- name: "Affichage du fallback Dynatrace"
  ansible.builtin.debug:
    msg: "{{ dt_generic.stdout_lines | default(['Fallback échoué']) }}"

- name: "Enregistrement du fallback Dynatrace"
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "INFO"
    set_results_component: "dynatrace"
    set_results_operation: "configure"
    set_results_value: "Fallback Dynatrace exécuté"
  ignore_errors: true
