---

- name: check WASND installation
  shell: test -f /apps/WebSphere85*/profiles/dmgr/bin/versionInfo.sh
  register: wasnd_install
  changed_when: false
  failed_when: false

- name: check WASND version
  shell: /apps/WebSphere85*/profiles/dmgr/bin/versionInfo.sh | grep -B 1 "ID" | grep -B 1 "ND" | grep Version | awk "{print \$2}"
  register: wasVersion
  changed_when: false
  failed_when: false
  become_user: was
  become_method: su
  become_flags: -l
  become: yes
  when: wasnd_install.rc == 0

- name: Format to Json when was nd is installed
  ansible.builtin.set_fact:
    tmp_json_wasnd: "{ \"installed\": \"yes\" ,\"version\": \"{{ wasVersion.stdout }}\" }"
  when: wasnd_install.rc == 0

- name: Format to Json when was nd is not installed
  ansible.builtin.set_fact:
    tmp_json_wasnd: "{ \"installed\": \"no\" ,\"version\": \"\" }"
  when: wasnd_install.rc != 0

- name: set result output for was nd check
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: ""
    set_results_value: "{{ tmp_json_wasnd | to_json | from_json }}" 
    set_results_component: "{{ wasnd_component }}"
    set_results_operation: "{{ wasnd_operation }}"
    set_results_role_name: "{{ wasnd_role_name }}"
    set_results_result_name: "{{ wasnd_result_name }}"
    set_results_status: "OK"


