---

- name: "List Environments"
  shell: "for was_app_serv in $(find /apps/WebSphere*/profiles/dmgr -name server.xml 2>/dev/null | grep sa- | awk -F '/' '{print$(NF-1)}' | sort -u);do find /applis/*/was -name ${was_app_serv} | awk -F '/' '{print$3}' | sort -u; done"
  register: list_env
  changed_when: false
  failed_when: false

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_component: "{{ wasnd_component }}"
    set_results_operation: "{{ wasnd_operation }}"
    set_results_role_name: "{{ wasnd_role_name }}"
    set_results_result_name: "{{ wasnd_result_name }}"
    set_results_item: ""
    set_results_state: "info"
    set_results_status: "OK"
    set_results_value: "{{ list_env.stdout_lines }}"

