---

- name: copy Manage script
  copy:
    src: WAS_Manage.ksh 
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: "restarting nodeagent"
  shell: "/applis/WAS_Manage.ksh restart nodeagent quiet"
  register: restart_lib_result
  changed_when: "'successfully' in restart_lib_result.stdout"
  failed_when: false

- set_fact:
     final_state: "restarted"
     state_value_json: ""
     final_status: "OK"

- set_fact:
     final_state: "not restarted"
     state_value_json: "dmgr binaries not found to restart nodeagent"
  when:
   - "'missing' in restart_lib_result.stdout"

- set_fact:
     final_state: "not restarted"
     final_status: "KO"
  when:
   - restart_lib_result.rc != 0
   - "'missing' not in restart_lib_result.stdout"

- name: set results output
  include_role:
    name: ips_toolbox_set_results
  vars:
     set_results_component: "{{ wasnd_component }}"
     set_results_operation: "{{ wasnd_operation }}"
     set_results_role_name: "{{ wasnd_role_name }}"
     set_results_result_name: "{{ wasnd_result_name }}"
     set_results_item: "nodeagent"
     set_results_state: "{{ final_state }}"
     set_results_status: "{{ final_status }}"
     set_results_value: "{{ state_value_json }}"

