---

- name: stop play when a mandatory variable is missing
  assert:
   that:
     - wasnd_item != ""
   msg: "wasnd_item variable is missing"

- name: copy Manage script
  copy:
    src: WAS_Manage.ksh 
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: "checking {{ wasnd_item }} status"
  shell: "/applis/WAS_Manage.ksh status {{ wasnd_item }} wnd"
  register: status_lib_result
  changed_when: false
  failed_when: false
  when: wasnd_ref != "yes"

- name: "checking {{ wasnd_item }} status with ref"
  shell: "/applis/WAS_Manage.ksh status_ref {{ wasnd_item }} wnd"
  register: status_lib_result2
  changed_when: false
  failed_when: false
  when: wasnd_ref == "yes"

- set_fact:
     state_value_json: ""
     final_state: "OK"

- set_fact:
     state_value_json: "{% if line_json.split(' ')[3] != \"STARTED\" %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"status\": \"stopped\" }{% else %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"status\": \"started\" }{% endif %}"
  loop: "{{ status_lib_result.stdout_lines }}"
  loop_control:
    loop_var: line_json
  when:
   - wasnd_ref != "yes"
   - status_lib_result.rc == 0
   - "'not found' not in status_lib_result.stdout"

- set_fact:
     state_value_json: "{% if line_json.split(' ')[3] != \"STARTED\" %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"status\": \"stopped\" }{% else %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"status\": \"started\" }{% endif %}"
  loop: "{{ status_lib_result2.stdout_lines }}"
  loop_control:
    loop_var: line_json
  when: 
   - wasnd_ref == "yes"
   - status_lib_result2.rc == 0
   - "'not found' not in status_lib_result2.stdout"

- set_fact:
    final_state: "KO"
  when:
    - wasnd_ref != "yes"
    - status_lib_result.rc != 0
    - "'not found' not in status_lib_result.stdout"

- set_fact:
    final_state: "KO"
  when:
    - wasnd_ref == "yes"
    - status_lib_result2.rc != 0
    - "'not found' not in status_lib_result2.stdout"

- name: set results output
  include_role:
    name: ips_toolbox_set_results
  vars:
     set_results_component: "{{ wasnd_component }}"
     set_results_operation: "{{ wasnd_operation }}"
     set_results_role_name: "{{ wasnd_role_name }}"
     set_results_result_name: "{{ wasnd_result_name }}"
     set_results_item: "{{ wasnd_item }}"
     set_results_state: "info"
     set_results_status: "{{ final_state }}" 
     set_results_value: "{% if wasnd_ref != 'yes' %}\

                           {% if 'not found' in status_lib_result.stdout %}\

                             application server not found\

                           {% else %}\

                             [ {{ state_value_json[1:] }} ]\

                           {% endif %}\

                         {% else %}\

                           {% if 'not found' in status_lib_result2.stdout %}\

                             application server not found\

                           {% else %}\

                             [ {{ state_value_json[1:] }} ]\

                           {% endif %}\

                         {% endif %}"


