---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - wasnd_item != ""
  msg: "wasnd_item variable is missing"

- name: Check toolbox version
  shell: test -f /apps/toolboxes/web/version && cat /apps/toolboxes/web/version | awk -F '|' '{print $2}' | sed 's/\.//g' || echo "0"
  register: tbxversion
  changed_when: false


- name: "stopped the Cluster WebSphere {{ wasnd_item }}"
  command: chdir=/apps/toolboxes/web/WasOperating/wasstartstop ./wasstartstop.ksh stop clt {{ wasnd_item }} "{{ wasnd_was_vi | default('85') }}"
  register: wasopr_result
  changed_when: "'already stopped' not in wasopr_result.stdout"
  when: tbxversion.stdout_lines[0]|int >= (17240|int)

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_item: "{{ wasnd_item }}"
    set_results_component: "{{ wasnd_component }}"
    set_results_operation: "{{ wasnd_operation }}"
    set_results_role_name: "{{ wasnd_role_name }}"
    set_results_result_name: "{{ wasnd_result_name }}"
    set_results_state: "{% if tbxversion.stdout_lines[0]|int >= (17240|int) %}\

                          {% if wasopr_result.rc == 0 %}\

                            stopped\

                          {% else %}\

                            not stopped\

                          {% endif %}\

                        {% else %}\

                          toolboxes under required version\

                        {% endif %}"
    set_results_status: "{% if tbxversion.stdout_lines[0]|int >= (17240|int) %}\

                          OK\

                        {% else %}\

                          KO\

                        {% endif %}"
    set_results_value: ""


