---
# Manage CFT monitor service

- name: Validate CFT action
  assert:
    that:
      - cft_action in ['start', 'stop', 'status']
    fail_msg: "cft_action must be 'start', 'stop', or 'status'"

- name: Get CFT status
  command: "{{ cft.runtime_path }}/bin/cft status"
  register: cft_status
  changed_when: false
  failed_when: false

- name: Stop CFT monitor
  command: "{{ cft.runtime_path }}/bin/cft stop"
  when: cft_action == 'stop'
  register: cft_stopped

- name: Start CFT monitor
  command: "{{ cft.runtime_path }}/bin/cft start"
  when: cft_action == 'start'
  register: cft_started

- name: Display CFT status
  debug:
    msg: "{{ cft_status.stdout_lines }}"
