---
- name: "Detect Illumio VEN"
  ansible.builtin.shell: |
    systemctl list-units --all | grep -q illumio-ven && echo "FOUND" || echo "MISSING"
  register: illu_srv
  changed_when: false

- name: "Configure Illumio VEN"
  ansible.builtin.shell: |
    if [ "{{ illu_srv.stdout }}" = "FOUND" ]; then
      echo "Activating VEN..."
      /opt/illumio_ven/illumio-ven-ctl activate
      echo "Setting enforcement to enforced..."
      /opt/illumio_ven/illumio-ven-ctl set-mode enforced
    else
      echo "Illumio VEN not installed, skipping."
    fi
  register: illu_cfg
  changed_when: false

- name: "Result Illumio"
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "{{ 'OK' if illu_srv.stdout == 'FOUND' else 'INFO' }}"
    set_results_component: "illumio"
    set_results_operation: "configure"
    set_results_value: "{{ 'Active & enforced' if illu_srv.stdout == 'FOUND' else 'Skipped' }}"
