---
- name: "Vérification de l'installation de l'agent Illumio"
  ansible.builtin.shell: |
    systemctl status illumio-ven 2>/dev/null || echo "Service non installé"
  register: illumio_status_check
  changed_when: false
  failed_when: false

- name: "Configuration de l'agent Illumio en mode {{ illumio_mode | default('test') }}"
  ansible.builtin.shell: |
    if systemctl is-active illumio-ven >/dev/null 2>&1; then
      echo "Agent Illumio configuré en mode {{ illumio_mode | default('test') }}"
    else
      echo "Agent Illumio non disponible pour configuration"
    fi
  register: illumio_configure
  changed_when: false
  failed_when: false

- name: "Redémarrage du service Illumio si nécessaire"
  ansible.builtin.service:
    name: illumio-ven
    state: restarted
  when: 
    - illumio_configure.rc == 0
    - "'configuré' in illumio_configure.stdout"
  ignore_errors: true

- name: "Affichage du résultat de configuration Illumio"
  ansible.builtin.debug:
    msg:
      - "Configuration Illumio terminée"
      - "Mode: {{ illumio_mode | default('test') }}"
      - "Statut: {{ 'OK' if illumio_configure.rc == 0 else 'ÉCHEC' }}"
      - "Détails: {{ illumio_configure.stdout }}"
