---

- name: "Vérification des variables obligatoires"
  ansible.builtin.assert:
    that:
      - system_codeAP is defined
      - system_codeAP != ""
      - system_code5car is defined
      - system_code5car != ""
    fail_msg: "Variables obligatoires manquantes : system_codeAP et system_code5car requis"
    success_msg: "Variables obligatoires présentes"

- name: "Affichage de la configuration"
  ansible.builtin.debug:
    msg:
      - "=== Création arborescence applicative via Toolbox ==="
      - "Code Application: {{ system_codeAP }}"
      - "Code 5 caractères: {{ system_code5car }}"
      - "Instance ID: {{ system_iis | default('01') }}"
      - "Volume Group: {{ system_vgName | default('vg_apps') }}"
      - "Taille LV: {{ system_lvSize | default('1024') }} Mo"

- name: "Vérification de l'existence du script Toolbox exploit_arbo-app.ksh"
  ansible.builtin.stat:
    path: "/apps/toolboxes/exploit/bin/exploit_arbo-app.ksh"
  register: toolbox_script_exists
  changed_when: false

- name: "Échec si le script Toolbox n'existe pas"
  ansible.builtin.fail:
    msg: |
      ❌ Le script Toolbox /apps/toolboxes/exploit/bin/exploit_arbo-app.ksh n'existe pas.
      Vérifiez que la Toolbox IPS est installée sur le serveur.
  when: not toolbox_script_exists.stat.exists

- name: "Construction des paramètres pour le script Toolbox"
  ansible.builtin.set_fact:
    toolbox_params:
      codeAP: "AP{{ system_codeAP }}"
      code5car: "{{ system_code5car }}"
      id: "{{ system_iis | default('01') }}"
      vg: "{{ system_vgName | default('vg_apps') }}"
      lv: "lv_{{ system_code5car }}:{{ system_lvSize | default('1024') }},lv_{{ system_code5car }}_ti:{{ system_lvSize | default('1024') }},lv_{{ system_code5car }}_to:{{ system_lvSize | default('1024') }}"

- name: "Affichage des paramètres Toolbox"
  ansible.builtin.debug:
    msg:
      - "=== Paramètres pour exploit_arbo-app.ksh ==="
      - "codeAP={{ toolbox_params.codeAP }}"
      - "code5car={{ toolbox_params.code5car }}"
      - "id={{ toolbox_params.id }}"
      - "vg={{ toolbox_params.vg }}"
      - "lv={{ toolbox_params.lv }}"

- name: "Exécution du script Toolbox exploit_arbo-app.ksh"
  ansible.builtin.shell: |
    /apps/toolboxes/exploit/bin/exploit_arbo-app.ksh \
      codeAP={{ toolbox_params.codeAP }} \
      code5car={{ toolbox_params.code5car }} \
      id={{ toolbox_params.id }} \
      vg={{ toolbox_params.vg }} \
      lv={{ toolbox_params.lv }}
  register: toolbox_execution
  changed_when: toolbox_execution.rc == 0
  failed_when: toolbox_execution.rc != 0

- name: "Affichage du résultat de l'exécution Toolbox"
  ansible.builtin.debug:
    msg:
      - "=== Résultat exploit_arbo-app.ksh ==="
      - "Code retour: {{ toolbox_execution.rc }}"
      - "Sortie standard:"
      - "{{ toolbox_execution.stdout_lines }}"

- name: "Vérification de la création de l'arborescence /applis"
  ansible.builtin.stat:
    path: "/applis/{{ toolbox_params.codeAP }}-{{ toolbox_params.code5car }}-{{ toolbox_params.id }}"
  register: applis_directory
  changed_when: false

- name: "Affichage du statut de création"
  ansible.builtin.debug:
    msg:
      - "=== Statut de création ==="
      - "Répertoire /applis/{{ toolbox_params.codeAP }}-{{ toolbox_params.code5car }}-{{ toolbox_params.id }}: {{ 'CRÉÉ ✅' if applis_directory.stat.exists else 'NON CRÉÉ ❌' }}"
      - "Permissions: {{ applis_directory.stat.mode | default('N/A') }}"
      - "Propriétaire: {{ applis_directory.stat.pw_name | default('N/A') }}"
      - "Groupe: {{ applis_directory.stat.gr_name | default('N/A') }}"

