---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - system_lvname != ""
    - system_addsize != ""
  msg: "at least one mandatory variable is missing beyond: system_lvname & system_addsize"


- name: extend lv {{ system_lvname }}
  shell: /apps/toolboxes/exploit/bin/exploit_extend-fs.ksh lv={{ system_lvname }} size="{{ system_addsize }}"
  register: extendfsresult
  changed_when: extendfsresult.rc == 0
  failed_when: false

- name: set result output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state:
    "{% if extendfsresult.rc == 0 %}\

        extended\

      {% else %}\

        not extended\

      {% endif %}"
    set_results_item: "{{ system_lvname }}" 
    set_results_value:
      "{% if extendfsresult.rc != 0 %}\

          {{ extendfsresult.stdout | regex_search('(-E-.*)') | replace('\u001b[0m','') }}\

      {% endif %}"
    set_results_component: "{{ system_component }}"
    set_results_operation: "{{ system_operation }}"
    set_results_role_name: "{{ system_role_name }}"
    set_results_result_name: "{{ system_result_name }}"
    set_results_status:
    "{% if extendfsresult.rc == 0 %}\

        OK\

      {% else %}\

        KO\

      {% endif %}"

