---
# Manage log rotation configuration

- name: Check if log rotation script exists
  stat:
    path: "{{ sha_toolbox_path }}/exploit/bin/exploit_rotate_log.ksh"
  register: log_rotate_script

- name: Display log rotation configuration
  debug:
    msg: "Log rotation script: {{ 'Available' if log_rotate_script.stat.exists else 'Not found' }}"

- name: Create logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/sha_{{ codeap }}_{{ codescar }}
    mode: '0644'
  when:
    - codeap is defined
    - codescar is defined
    - log_paths is defined

- name: Test log rotation configuration
  command: logrotate -d /etc/logrotate.d/sha_{{ codeap }}_{{ codescar }}
  register: logrotate_test
  changed_when: false
  when: codeap is defined and codescar is defined

- name: Display log rotation test results
  debug:
    var: logrotate_test.stdout_lines
  when: logrotate_test is defined
