---

- set_fact:
    system_component: "{{ role_name.split('_')[-1] }}"
    system_role_name: "{{ role_name }}"

- name: include tasks operation

  block:

  - local_action: stat path={{ role_path }}/tasks/{{ system_task_file_name }}
    become: no
    register: statResult
    failed_when: statResult.stat.exists == false

  - include_tasks: "{{ system_task_file_name }}"
    when: statResult.stat.exists

  rescue:

  - name: set result failed operation
    include_role:
      name: ips_toolbox_set_results
    vars:
      set_results_state: "info"
      set_results_item: ""
      set_results_component: "{{ system_component }}"
      set_results_operation: "{{ system_operation }}"
      set_results_role_name: "{{ system_role_name }}"
      set_results_status: "KO"
      set_results_value: "\

        {% if statResult.stat.exists == false %}\

          task {{ system_task_file_name }} does not exist\

        {% else %}\

          task execution error\

        {% endif %}"
