---
- name: "Initialisation du rôle ips_toolbox_system"
  ansible.builtin.set_fact:
    system_component: "system"
    system_role_name: "ips_toolbox_system"

- name: "Construction du nom de fichier de tâche système"
  ansible.builtin.set_fact:
    system_task_file_name: "{{ system_operation | default('status') }}_{{ ansible_system }}_system.yml"

- name: "Vérification de l'existence de la tâche système demandée"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ system_task_file_name }}"
  register: system_task_file_check
  delegate_to: localhost

- name: "Exécution de la tâche système spécifique"
  block:
    - name: "Inclusion de la tâche système {{ system_task_file_name }}"
      ansible.builtin.include_tasks: "{{ system_task_file_name }}"
      when: system_task_file_check.stat.exists
  rescue:
    - name: "Gestion de l'erreur - Tâche système introuvable"
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "KO"
        set_results_component: "{{ system_component }}"
        set_results_operation: "{{ system_operation | default('status') }}"
        set_results_value: "Fichier {{ system_task_file_name }} introuvable ou erreur d'exécution"

- name: "Fallback - Tâche générique si fichier spécifique introuvable"
  ansible.builtin.include_tasks: "status_generic_system.yml"
  when: not system_task_file_check.stat.exists

- name: "Affichage du statut d'exécution du rôle système"
  ansible.builtin.debug:
    msg:
      - "Rôle système exécuté"
      - "Fichier: {{ system_task_file_name if system_task_file_check.stat.exists else 'status_generic_system.yml' }}"
      - "Opération: {{ system_operation | default('status') }}"
      - "OS: {{ ansible_system }}"
