---
- name: "Initialisation du rôle ips_toolbox_system"
  set_fact:
    system_component: "{{ role_name.split('_')[-1] }}"
    system_role_name: "{{ role_name }}"

- name: "Inclure la tâche système demandée"
  block:
    - name: "Vérification de l'existence de la tâche {{ system_task_file_name }}"
      stat:
        path: "{{ role_path }}/tasks/{{ system_task_file_name }}"
      register: statResult

    - name: "Exécution de la tâche système {{ system_task_file_name }}"
      include_tasks: "{{ system_task_file_name }}"
      when: statResult.stat.exists
  rescue:
    - name:  
        - "Le fichier de tâche système {{ system_task_file_name }} est introuvable"
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "KO"
        set_results_component: "{{ system_component }}"
        set_results_operation: "{{ system_operation }}"
        set_results_value: "Fichier {{ system_task_file_name }} introuvable"
