---

- name: sanity check for fs
  shell: /apps/sys/admin/AixSanityCheck.ksh lvm
  register: sanityresult
  changed_when: false
  failed_when: false

- name: sanity check result
  shell: /apps/sys/admin/AixSanityCheck.ksh report
  changed_when: false
  register: sanitycsv
  when:
    - sanityresult.rc == 0

- name: init Json
  set_fact:
    tmp_json: ""
  when:
    - sanityresult.rc == 0

- name: Format to Json
  set_fact:
    tmp_json: "{{ tmp_json }}, { \"code\": \"{{ line.split('|')[1] | regex_replace('^[ ]+','') }}\" ,\"instance\": \"{{ line.split('|')[2] | regex_replace('^[ ]+','') }}\",\"parameter\": \"{{ line.split('|')[3] | regex_replace('^[ ]+','') }}\" ,\"actualvalue\": \"{{ line.split('|')[4] | regex_replace('^[ ]+','') }}\" ,\"refvalue\": \"{{ line.split('|')[5] | regex_replace('^[ ]+','') }}\" ,\"count\": \"{{ line.split('|')[6] | regex_replace('^[ ]+','') }}\" }"
  loop: "{{ sanitycsv.stdout_lines | select('match', '\\|[^-].*') | list }}"
  loop_control:
    loop_var: line
  when:
    - sanityresult.rc == 0

- name: End Json
  set_fact:
    tmp_json2: "{{ tmp_json[2:] }}"
  when:
    - sanityresult.rc == 0

- name: set result output
  include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state:
     "{% if sanityresult.rc == 0 %}\

         {% if tmp_json2[1:] != '' %}\

            anomalie detected\

         {% else %}\

            no anomalie detected\

         {% endif %}\

      {% else %}\

         not executed\

      {% endif %}"
    set_results_item: ""
    set_results_value: 
     "{% if sanityresult.rc == 0 %}\

         {{ tmp_json2[1:] }}\

      {% else %}\

         {{ sanityresult.stderr_lines }}\

      {% endif %}"
    set_results_component: "{{ system_component }}"
    set_results_operation: "{{ system_operation }}"
    set_results_role_name: "{{ system_role_name }}"
    set_results_result_name: "{{ system_result_name }}"
    set_results_status:
     "{% if sanityresult.rc == 0 %}\

         OK\

      {% else %}\

         KO\

      {% endif %}"

