---

- name: get full release name
  shell: echo "$(oslevel | cut -d'.' -f1,2) TL$(oslevel -r | cut -c7)"
  changed_when: False
  register: description2
  when: ansible_lsb.description is undefined

- name: get uptime
  shell: uptime | awk -F"," '{print$1}' | grep day | awk -F" " '{print$3}'
  changed_when: False
  register: uptimesystem

- name: get cpu clock speed
  shell: prtconf -s | awk '{ print $4 " " $5 }'
  changed_when: False
  register: clock_speed

- name: get vgs names
  shell: lsvg -o
  changed_when: False
  register: vgnames_output

- name: get vgs's block_size
  shell: lsvg {{ item }} | awk '/PP SIZE:/ { print $(NF-1) }' 2> /dev/null 
  with_items: "{{ vgnames_output.stdout_lines | list }}"
  changed_when: False
  register: block_size_output


- name: set blocksize per vg
  set_fact:
    blocksizeVG: "{{ blocksizeVG|default({}) | combine( { (item.item | trim ) : item.stdout } )}}"
  with_items: "{{ block_size_output.results }}"

- name: set result output
  include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: "" 
    set_results_value: "{{ lookup('template', 'system_AIX_info.json.j2') }}"
    set_results_component: "{{ system_component }}"
    set_results_operation: "{{ system_operation }}"
    set_results_role_name: "{{ system_role_name }}"
    set_results_result_name: "{{ system_result_name }}"
    set_results_status: "OK"

