---

- name: get full release name
  shell: cat /etc/redhat-release
  changed_when: False
  register: description2
  when: ansible_lsb.description is undefined

- name: get cpu clock speed
  shell: grep "^cpu MHz" /proc/cpuinfo | awk '{print $NF}' | tail -n 1 | cut -d"." -f1
  changed_when: False
  register: clock_speed

- name: get vgs names
  shell: vgs --noheadings -o vg_name
  changed_when: False
  register: vgnames_output

- name: get vgs's block_size
  shell: vgs --noheadings {{ item | trim }} --units m -o vg_extent_size | cut -d'.' -f1 | awk '{ print $NF }' 
  with_items: "{{ vgnames_output.stdout_lines | list }}"
  changed_when: False
  register: block_size_output


- name: set blocksize per vg
  ansible.builtin.set_fact:
    blocksizeVG: "{{ blocksizeVG|default({}) | combine( { (item.item | trim ) : item.stdout } )}}"
  with_items: "{{ block_size_output.results }}"

- name: set result output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: "" 
    set_results_value: "{{ lookup('template', 'system_Linux_info.json.j2') }}"
    set_results_component: "{{ system_component }}"
    set_results_operation: "{{ system_operation }}"
    set_results_role_name: "{{ system_role_name }}"
    set_results_result_name: "{{ system_result_name }}"
    set_results_status: "OK"

