---

- name: Check if uptime is more than 24h
  shell: uptime | awk -F"," '{print$1}' | grep day
  failed_when: false
  changed_when: false
  register: uptime_day

- name: If uptime is more than 24h check how many days
  shell: uptime | awk -F"," '{print$1}' | grep day | awk -F" " '{print$3}'
  failed_when: false
  changed_when: false
  register: uptime_day_value
  when: uptime_day.rc == 0

- name: set result output
  include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "{% if uptime_day.rc != 0 %}Compliant{% else %}{% if (uptime_day_value.stdout) | int < (system_uptime_limit | int ) %}Compliant{% else %}Not compliant{% endif %}{% endif %}"
    set_results_item: ""
    set_results_value: "{% if uptime_day.rc != 0 %}\

                         0 day\

                        {% else %}\

                         {{ (uptime_day_value.stdout) | int }} day(s)\

                        {% endif %}"
    set_results_component: "{{ system_component }}"
    set_results_operation: "{{ system_operation }}"
    set_results_role_name: "{{ system_role_name }}"
    set_results_result_name: "{{ system_result_name }}"
    set_results_status: "OK"

