---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - webserver_kdb_path != ""
  msg: "The mandatory variable webserver_kdb_path is missing"

- name: copy script to check certificates expiration date
  ansible.builtin.copy:
    src: see_expiration_date_cert.ksh
    dest: /apps/toolboxes/web/ManageCertificates/tools
    mode: 0775
    owner: root
    group: web

- name: "Check certificates expiration date"
  shell: /apps/toolboxes/web/ManageCertificates/tools/see_expiration_date_cert.ksh cmd {{ webserver_kdb_path }} {{ webserver_kdb_pwd }} quiet
  register: info_certif
  changed_when: "false"
  failed_when: false

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_item: ""
    set_results_component: "{{ webserver_component }}"
    set_results_operation: "{{ webserver_operation }}"
    set_results_role_name: "{{ webserver_role_name }}"
    set_results_result_name: "{{ webserver_result_name }}"
    set_results_state: "info"
    set_results_status: "{% if info_certif.rc == 0 %}\

                          OK\

                        {% else %}\

                          KO\

                        {% endif %}"
    set_results_value: "{% if info_certif.rc == 0 %}\

                          {{ info_certif.stdout_lines }}\

                        {% else %}\

                          Error\

                        {% endif %}"

