---

- name: stop play when a mandatory variable is missing
  assert:
   that:
     - webserver_kdb_path != ""
     - webserver_crt_file != ""
     - webserver_grp_type != ""
   msg: "At least one variable is missing beyond webserver_kdb_path webserver_crt_file or webserver_grp_type"

- name: Check toolbox version
  shell: test -f /apps/toolboxes/version && cat /apps/toolboxes/version | awk -F '|' '{print $2}' | sed 's/\.//g' || echo "0"
  register: tbxversion
  changed_when: false

- name: certificate deposit
  copy:
   src: "{{ webserver_crt_file }}"
   dest: /apps/toolboxes/web/ManageCertificates/tmp
  changed_when: false
  when: tbxversion.stdout_lines[0]|int >= (1922|int) 

- name: "generate CSR"
  shell: /apps/toolboxes/web/ManageCertificates/tools/reception_Certif.ksh cmd {{ webserver_kdb_path }} /apps/toolboxes/web/ManageCertificates/tmp {{ webserver_grp_type }} {{ webserver_kdb_pwd }} 
  register: cert_insert
  changed_when: "'successfully imported' in cert_insert.stdout"
  failed_when: false
  when: tbxversion.stdout_lines[0]|int >= (1922|int)

- name: set results output
  include_role:
    name: ips_toolbox_set_results
  vars:
     set_results_item: "{{ webserver_crt_file }}"
     set_results_component: "{{ webserver_component }}"
     set_results_operation: "{{ webserver_operation }}"
     set_results_role_name: "{{ webserver_role_name }}"
     set_results_result_name: "{{ webserver_result_name }}"
     set_results_state: "{% if tbxversion.stdout_lines[0]|int >= (1922|int) %}\

                           {% if cert_insert.rc == 0 %}\

                             OK\

                           {% else %}\

                             KO\

                           {% endif %}\

                         {% else %}\

                           KO\

                         {% endif %}"
     set_results_status: "OK"
     set_results_value: "{% if tbxversion.stdout_lines[0]|int >= (1922|int) %}\

                           {% if cert_insert.rc == 0 %}\

                             CRT file inserted in {{ webserver_kdb_path  }}\

                           {% else %}\

                             Error encountered. Check cert_insert.stdout for details\

                           {% endif %}\

                         {% else %}\

                           toolboxes under required version\

                         {% endif %}"


