---

- set_fact:
    webserver_component: "{{ role_name.split('_')[-1] }}"
    webserver_role_name: "{{ role_name }}"

- name: "collect filenames dynamically"
  ansible.builtin.set_fact:
    task_directory_files: "{{ lookup('fileglob', '{{ role_path }}/tasks/*.yml').split(',') | map('basename') | list | reject('match', 'main.yml' ) | list }}"
    file_name: "{{ webserver_task_file_name }}"

- name: include tasks operation

  block:
  - include_tasks: "{{ webserver_task_file_name }}"
    when: file_name in task_directory_files

  rescue:

  - name: set result failed operation
    ansible.builtin.include_role:
      name: ips_toolbox_set_results
    vars:
      set_results_state: "info"
      set_results_item: ""
      set_results_component: "{{ webserver_component }}"
      set_results_operation: "{{ webserver_operation }}"
      set_results_role_name: "{{ webserver_role_name }}"
      set_results_status: "KO"
      set_results_value: "\

        {% if statResult.stat.exists == false %}\

          task {{ webserver_task_file_name }} does not exist\

        {% else %}\

          task execution error\

        {% endif %}"

