---
# List Oracle instances from /etc/oratab

- name: Read oratab file
  command: cat {{ oracle.oratab_path }}
  register: oratab_content
  changed_when: false

- name: Parse Oracle instances
  set_fact:
    oracle_instances: "{{ oratab_content.stdout_lines | select('match', '^[^#].*:.*:.*') | list }}"

- name: Display Oracle instances
  debug:
    msg:
      - "Oracle instances found:"
      - "{{ oracle_instances }}"

- name: Set instance count
  set_fact:
    instance_count: "{{ oracle_instances | length }}"

- name: Display instance count
  debug:
    msg: "Total Oracle instances: {{ instance_count }}"
