---

- name: Check presence oratab
  ansible.builtin.stat:
    path: "/etc/oratab"
  register: file_info

- name: Nombre instance oracle
  shell: awk -F':' '$1 ~/^[A-Za-z]/{print $1}' /etc/oratab | grep -v AGENT | wc -l
  register: nb_instance
  changed_when: false
  when:
    - file_info.stat.exists == true

- name: List instance oracle
  shell: awk -F':' '$1 ~/^[A-Za-z]/{print $1}' /etc/oratab | grep -v AGENT
  register: list_instance
  changed_when: false
  when:
    - file_info.stat.exists == true
    - nb_instance.stdout[0]|int > 0

- name: set result output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "\

      {% if file_info.stat.exists == true %}\

          {% if list_instance.rc is defined %}\

            Listed\

          {% else %}\

            Not listed\

          {% endif %}\

      {% else %}\

          Not listed\

      {% endif %}"
    set_results_item: ""
    set_results_value: "\

      {% if file_info.stat.exists == true %}\

          {% if list_instance.rc is defined %}\

            {{ list_instance.stdout_lines }}\

          {% else %}\

            oratab empty\

          {% endif %}\

      {% else %}\

          oratab not found\

      {% endif %}"
    set_results_component: "{{ oracle_component }}"
    set_results_operation: "{{ oracle_operation }}"
    set_results_role_name: "{{ oracle_role_name }}"
    set_results_result_name: "{{ oracle_result_name }}"
    set_results_status: "OK"

