---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - oracle_item != ""
  msg: "oracle_item variable is missing"

- name: Begin list_tablespace oracle
  no_log: true
  block:

    - name: check presence instance
      shell: 'if [ "{{ oracle_item }}" = "all" ];then egrep -v "^#|^$|^\*" /etc/oratab | cut -d: -f1;else egrep -v "^#|^$|^\*" /etc/oratab | cut -d: -f1 | grep -w ^{{ oracle_item }};fi'
      register: checkPresence
      failed_when: false
      changed_when: false

    - name: get information
      oracle_tablespace:
        action: get
        instanceName: "{{ oracle_item }}"
      become: true
      become_user: oracle
      become_method: su
      register: list_tablespaces
      when:
        - checkPresence.rc == 0

    - name: working list_tablespace {{ oracle_item }}
      ansible.builtin.set_fact:
        oracle_status: "OK"
        oracle_value: "{{ list_tablespaces.tablespaces }}"
        oracle_state: "listed"
        oracle_item: "{% if oracle_item is defined %}{{ oracle_item }}{% endif %}"
      when:
        - checkPresence.rc == 0
        - list_tablespaces.rc == 0


    - name: not working list_tablespace {{ oracle_item }}
      ansible.builtin.set_fact:
        oracle_status: "OK"
        oracle_value: "{{ list_tablespaces.message }}"
        oracle_state: "not listed"
        oracle_item: "{% if oracle_item is defined %}{{ oracle_item }}{% endif %}"
      when:
        - checkPresence.rc == 0
        - list_tablespaces.rc != 0
   
      
    - name: "{{ oracle_item }} not found"
      ansible.builtin.set_fact:
        oracle_status: "OK"
        oracle_state: "not listed"     
        oracle_value: "instance {{ oracle_item }} not found"  
        oracle_item: "{% if oracle_item is defined %}{{ oracle_item }}{% endif %}"
      when:
        - checkPresence.rc != 0
      
  rescue:
    - name: ansible failure
      ansible.builtin.set_fact:
        oracle_status: "KO"
        oracle_value: "{% if list_tablespaces.message is defined %}{{ list_tablespaces.message }}{% endif %}"
        oracle_state: "not listed"
        oracle_item: "{% if oracle_item is defined %}{{ oracle_item }}{% endif %}"
  always:
    - name: End list_tablespace oracle
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "{{ oracle_state }}"
        set_results_item: "{{ oracle_item }}"
        set_results_component: "{{ oracle_component }}"
        set_results_operation: "{{ oracle_operation }}"
        set_results_role_name: "{{ oracle_role_name }}"
        set_results_value: "{{ oracle_value }}"
        set_results_result_name: "{{ oracle_result_name }}"
        set_results_status: "{{ oracle_status }}"        

