---


system_codeAP: ""
system_code5car: ""
system_component: ""
system_operation: ""
system_task_file_name: "{{ system_operation }}_{{ ansible_system }}_{{ system_component }}.yml"
system_script_mode: false
system_lvname: ""
system_addsize: ""

system_uptime_limit: 90
system_stop_timeout: 600
system_restart_timeout: 600
system_uptime_max: 10

system_Appli_Code: "{{ system_codeAP }}"
system_Appli_5_car: "{{ system_code5car }}"
system_Appli_IIS: "{{ system_iis | default('False') }}"
system_Appli_id: "{% if system_idappli is defined %}\

                id={{ system_idappli }}\

           {% endif %}"
system_Appli_vg: "{% if system_vgName is defined %}\

                vg={{ system_vgName }}\

           {% endif %}"

system_Appli_lv: "{% if (system_lvSize) is defined %}\

              lv=lv_{{ system_code5car }}:{{ system_lvSize }},lv_{{ system_code5car }}_ti:{{ system_lvSize }},lv_{{ system_code5car }}_to:{{ system_lvSize }},lv_{{ system_code5car }}_tmp:{{ system_lvSize }},lv_{{ system_code5car }}_arch:{{ system_lvSize }},lv_log_{{ system_code5car }}:{{ system_lvSize }},lv_shared:{{ system_lvSize }},lv_shared_tmp:{{ system_lvSize }},lv_shared_arch:{{ system_lvSize }},lv_log_shared:{{ system_lvSize }},lv_dlv_shared:{{ system_lvSize }},lv_dlv_{{ system_code5car }}:{{ system_lvSize }}\

           {% endif %}"

system_Appli_lvex: "{% if system_lvEx is defined %}\

                exclude={{ system_lvEx }}\

           {% endif %}"
system_Appli_lvex1: "{% if system_lvEx1 is defined %}\

                ,{{ system_lvEx1 }}\

           {% endif %}"
system_Appli_lvex2: "{% if system_lvEx2 is defined %}\

                ,{{ system_lvEx2 }}\

           {% endif %}"
system_Appli_user: "{% if system_username is defined %}\

                {% if system_group is defined %}\

                   {% if system_NNN is defined %}\

                    user={{ system_username }}:{{ system_group }},{{ system_NNN }}\

                {% endif %}\

                   {% endif %}\

           {% endif %}"

system_result_name: ""
system_stat_exist: ""

system_create_filename: ""
system_create_lvname: ""
system_create_fsname: ""
system_create_lvsize: ""
system_create_vg: "{% if system_create_vgname is defined %}\

                       {{ system_create_vgname }}\

                       {% else %}\

                       vg_apps\

                       {% endif %}"
system_create_user: "{% if system_create_username is defined %}\

                         {{ system_create_username }}\

                         {% else %}\

                         0\

                         {% endif %}"
system_create_group: "{% if system_create_groupname is defined %}\

                         {{ system_create_groupname }}\

                         {% else %}\

                         0\

                         {% endif %}"
system_create_mwtype: "{% if system_create_middlewaretype is defined %}\

                       {{ system_create_middlewaretype }}\

                       {% endif %}"
system_create_ftype: "{% if system_create_filetype is defined %}\

                      {{ system_create_filetype }}\

                      {% endif %}"

