---
# Example: Manage filesystems

- name: Filesystem Management Examples
  hosts: rhel_servers
  become: yes
  gather_facts: yes

  tasks:
    # Example 1: Create a new filesystem
    - name: Create filesystem for application data
      include_role:
        name: ips_toolbox_system
      vars:
        filesystem_action: create
        codeap: "12345"
        codescar: "APP01"
        vg_name: vg_apps
        size: 5
        mount_point: "/applis/12345-APP01"
        lv_name: "lv_APP01"

    # Example 2: Extend existing filesystem
    - name: Extend filesystem
      include_role:
        name: ips_toolbox_system
      vars:
        filesystem_action: extend
        lv_name: "lv_APP01"
        vg_name: vg_apps
        size: 2  # Add 2GB
        mount_point: "/applis/12345-APP01"

    # Example 3: Create transfer directories with dedicated filesystems
    - name: Create transfer IN filesystem
      include_role:
        name: ips_toolbox_system
      vars:
        filesystem_action: create
        lv_name: "lv_APP01_ti"
        vg_name: vg_apps
        mount_point: "/applis/12345-APP01/transfer/in"
        size: 10

    - name: Create transfer OUT filesystem
      include_role:
        name: ips_toolbox_system
      vars:
        filesystem_action: create
        lv_name: "lv_APP01_to"
        vg_name: vg_apps
        mount_point: "/applis/12345-APP01/transfer/out"
        size: 10
