---

- name: copy Manage script
  ansible.builtin.copy:
    src: WAS_Manage.ksh
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: "listing application servers"
  shell: "/applis/WAS_Manage.ksh list all_sa wba quiet | sed -e 's/^WBA: //g' | awk '{print$1}'"
  register: list_lib_result
  changed_when: false

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_component: "{{ wasbase_component }}"
    set_results_operation: "{{ wasbase_operation }}"
    set_results_role_name: "{{ wasbase_role_name }}"
    set_results_result_name: "{{ wasbase_result_name }}"
    set_results_item: "{{ wasbase_item }}"
    set_results_state: "info"
    set_results_status: "OK"
    set_results_value: "\

          {% if list_lib_result.stdout != ''%}\

            {{ list_lib_result.stdout_lines }}\

          {% else %}\

            application server not found\

          {% endif %}"

