---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - wasbase_item != ""
  msg: "wasbase_item variable is missing"

- name: copy Manage script
  ansible.builtin.copy:
    src: WAS_Manage.ksh 
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: "stopping {{ wasbase_item }}"
  shell: "/applis/WAS_Manage.ksh stop {{ wasbase_item }} wba quiet"
  register: stop_lib_result
  changed_when: "'successfully' in stop_lib_result.stdout"
  failed_when: false

- set_fact:
    state_value_json: ""
    final_state: "stopped"
    final_status: "OK"

- set_fact:
    final_state: "not stopped"
    state_value_json: "application server not found"
  when:
  - "'not found' in stop_lib_result.stdout"

- set_fact:
    state_value_json: ""
    final_state: "unknown"
    final_status: "KO"
  when:
  - stop_lib_result.rc != 0

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_component: "{{ wasbase_component }}"
    set_results_operation: "{{ wasbase_operation }}"
    set_results_role_name: "{{ wasbase_role_name }}"
    set_results_result_name: "{{ wasbase_result_name }}"
    set_results_item: "{{ wasbase_item }}"
    set_results_state: "{{ final_state }}"
    set_results_status: "{{ final_status }}"
    set_results_value: "{{ state_value_json }}"

