---
# Manage IHS SSL certificates

- name: Validate certificate action
  assert:
    that:
      - cert_action in ['create', 'import', 'list', 'delete', 'check_expiry']
    fail_msg: "Invalid cert_action"

- name: Create keystore and CSR
  block:
    - name: Generate keystore
      command: >
        {{ websphere.ihs_root }}/bin/gskcapicmd -keydb -create
        -db {{ keystore_path }}/{{ keystore_name }}.kdb
        -pw {{ keystore_password }}
        -type cms
        -stash
      when: cert_action == 'create'

    - name: Create certificate request
      command: >
        {{ websphere.ihs_root }}/bin/gskcapicmd -certreq -create
        -db {{ keystore_path }}/{{ keystore_name }}.kdb
        -pw {{ keystore_password }}
        -label {{ cert_label }}
        -dn "{{ cert_dn }}"
        -file {{ keystore_path }}/{{ cert_label }}.csr
      when: cert_action == 'create'

    - name: Display CSR location
      debug:
        msg: "CSR created at {{ keystore_path }}/{{ cert_label }}.csr"

- name: Import certificate
  command: >
    {{ websphere.ihs_root }}/bin/gskcapicmd -cert -add
    -db {{ keystore_path }}/{{ keystore_name }}.kdb
    -pw {{ keystore_password }}
    -file {{ cert_file }}
    -label {{ cert_label }}
  when:
    - cert_action == 'import'
    - cert_file is defined

- name: List certificates
  command: >
    {{ websphere.ihs_root }}/bin/gskcapicmd -cert -list
    -db {{ keystore_path }}/{{ keystore_name }}.kdb
    -pw {{ keystore_password }}
  register: cert_list
  changed_when: false
  when: cert_action == 'list'

- name: Display certificates
  debug:
    msg: "{{ cert_list.stdout_lines }}"
  when: cert_action == 'list'

- name: Check certificate expiry
  command: >
    {{ websphere.ihs_root }}/bin/gskcapicmd -cert -details
    -db {{ keystore_path }}/{{ keystore_name }}.kdb
    -pw {{ keystore_password }}
    -label {{ cert_label }}
  register: cert_details
  changed_when: false
  when: cert_action == 'check_expiry'

- name: Display certificate expiry
  debug:
    msg: "{{ cert_details.stdout_lines }}"
  when: cert_action == 'check_expiry'
