---
all:
  children:
    linux_servers:
      children:
        rhel_servers:
          hosts:
            # PRODUCTION RHEL servers

    windows_servers:
      children:
        windows_2019:
          hosts:
            # PRODUCTION Windows servers

    websphere_servers:
      children:
        was_nd:
          hosts:
        was_base:
          hosts:
        liberty_core:
          hosts:
        liberty_base:
          hosts:

    database_servers:
      children:
        oracle_servers:
          hosts:
        sqlserver_servers:
          hosts:

    middleware_servers:
      children:
        cft_servers:
          hosts:
        mq_servers:
          hosts:

  vars:
    ansible_user: ansible
    ansible_become: yes
    ansible_become_method: sudo
    environment_name: prod
