---
- name: "Validation des variables pour la génération JSON"
  ansible.builtin.assert:
    that:
      - environment_type is defined
      - execution_report is defined
    fail_msg: "Variables requises manquantes pour la génération JSON"

- name: "Initialisation des variables manquantes pour le rapport"
  ansible.builtin.set_fact:
    execution_report: "{{ execution_report | combine({
      'execution_metadata': execution_report.execution_metadata | default({}) | combine({
        'execution_id': execution_id | default(ansible_date_time.epoch),
        'hostname': inventory_hostname,
        'environment': environment_type,
        'start_time': execution_timestamp | default(ansible_date_time.iso8601),
        'end_time': ansible_date_time.iso8601
      })
    }, recursive=True) }}"

- name: "Consolidation finale du rapport JSON"
  ansible.builtin.set_fact:
    final_json_report:
      metadata:
        report_type: "SHA Application Environment Builder"
        environment: "{{ environment_type }}"
        hostname: "{{ inventory_hostname }}"
        execution_id: "{{ execution_report.execution_metadata.execution_id }}"
        start_time: "{{ execution_report.execution_metadata.start_time }}"
        end_time: "{{ execution_report.execution_metadata.end_time }}"
        ansible_version: "{{ ansible_version.full }}"
        playbook_version: "{{ execution_report.execution_metadata.playbook_version | default('2.1') }}"
      system_detection: "{{ execution_report.system_detection | default({}) }}"
      infrastructure_changes: "{{ execution_report.infrastructure_changes | default({}) }}"
      compliance_validation: "{{ execution_report.compliance_validation | default({}) }}"
      execution_results: "{{ execution_report.execution_results | default({}) }}"

- name: "Création du répertoire de rapport si inexistant"
  ansible.builtin.file:
    path: "{{ report_dir | default('/tmp/ansible_reports') }}"
    state: directory
    mode: '0755'

- name: "Création du fichier de rapport JSON"
  ansible.builtin.copy:
    content: "{{ final_json_report | to_nice_json(indent=2) }}"
    dest: "{{ report_dir | default('/tmp/ansible_reports') }}/execution_report_{{ execution_report.execution_metadata.execution_id }}.json"
    mode: '0644'
  register: json_report_created

- name: "Affichage de la confirmation de création du rapport JSON"
  ansible.builtin.debug:
    msg:
      - "Rapport JSON généré avec succès"
      - "Fichier: {{ report_dir | default('/tmp/ansible_reports') }}/execution_report_{{ execution_report.execution_metadata.execution_id }}.json"
      - "Taille: {{ (final_json_report | to_nice_json | length / 1024) | round(1) }} KB"
