---
  
- name: check tsm installation and version
  shell: dsmc show version | grep "Client Version" | sort -u
  register: tsmVersion
  changed_when: false
  failed_when: false

- name: Format to Json when tsm is installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"yes\" ,\"version\": \"{{ tsmVersion.stdout | trim }}\" }"
  when:
    - tsmVersion.stderr == ""

- name: Format to Json when tsm is not installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"no\" ,\"version\": \"\" }"
  when:
    - tsmVersion.stderr | regex_search('command not found')


- name: set result output for tsm check
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state: "info"
    set_results_item: ""
    set_results_value: "{{ tmp_json | to_json | from_json }}"
    set_results_component: "{{ tsm_component }}"
    set_results_operation: "{{ tsm_operation }}"
    set_results_role_name: "{{ tsm_role_name }}"
    set_results_result_name: "{{ tsm_result_name }}"
    set_results_script_mode: "{{ tsm_script_mode }}"
    set_results_status:
      "{% if tsmVersion.rc == 0 %}\

        OK\

      {% else %}\

        KO\

      {% endif %}"


