---

- name: Begin retrieving information
  block:
  
    - name: Check tsm installed
      ansible.builtin.find:
        paths: "/usr/tivoli/tsm/client/ba"
        patterns: "dsmc"
        recurse: yes
      register: tsmbinchk

    - name: get list class
      shell: "dsmc qu mgmt | awk -F ': ' '{print $2}' | grep -E '^ARCH|^BAA_' | grep -E '[A-Z]$' | grep -Ev 'ARCH.*_|AN'"
      register: ArchClass
      changed_when: false
      when:
        - tsmbinchk.matched > 0
      failed_when:
        - ArchClass.rc != 0 or ArchClass.stdout == ""

    - name: get default backup class
      shell: "dsmc q mgmt -detail | grep 'Default Mgmt Class Name' | awk '{print $NF}'"
      register: DefaultBackupClass
      changed_when: false
      when:
        - tsmbinchk.matched > 0
      failed_when:
        - DefaultBackupClass.rc != 0 or DefaultBackupClass.stdout == ""

    - name: get default backup class details
      shell: "dsmc q mgmt -detail | awk /[.]*{{ DefaultBackupClass.stdout }}/,/^$/ | awk '/MgmtClass Name/,/^$/' | egrep 'Versions Data|Retain .+Version.*' | sed 's/.*Versions /Versions /g' | sed 's/.*Retain /Retain /g' | sed 's/\\.//g'"
      register: DefaultBackupClassDetails
      changed_when: false
      when:
        - tsmbinchk.matched > 0
      failed_when:
        - DefaultBackupClassDetails.rc != 0 or DefaultBackupClassDetails.stdout == ""

    - name: initiate tmp json
      ansible.builtin.set_fact:
        tmp_json1: "\"mgmt class name\": \"{{ DefaultBackupClass.stdout }}\""
      when:
        - tsmbinchk.matched > 0

    - name: Format to json
      ansible.builtin.set_fact:
        tmp_json1: "{{ tmp_json1 }}, \"{{ line_json.split(':')[0] }}\": \"{{ line_json.split(':')[1] | trim }}\""
      loop: "{{ DefaultBackupClassDetails.stdout_lines | list }}"
      loop_control:
        loop_var: line_json
      when:
        - tsmbinchk.matched > 0

    - name: success retrieving of information 
      ansible.builtin.set_fact:
        tsm_status: "OK"
        tsm_value: "{% if tsmbinchk.matched > 0 %}{ \"archive classes\": [ {{ ArchClass.stdout_lines }} ], \"default backup class\": { {{ tmp_json1 }} } }{% else %}tsm is not installed{% endif %}"

  rescue:
    - name: ansible failure
      ansible.builtin.set_fact:
        tsm_status: "KO"
        tsm_value: "Error while retrieving information"

  always:
    - name: set result output for list classes
      ansible.builtin.include_role:
        name: ips_toolbox_set_results
      vars:
        name: results
        set_results_state: "info"
        set_results_item: ""
        set_results_value: "{{ tsm_value }}"
        set_results_component: "{{ tsm_component }}"
        set_results_operation: "{{ tsm_operation }}"
        set_results_role_name: "{{ tsm_role_name }}"
        set_results_result_name: "{{ tsm_result_name }}"
        set_results_script_mode: "{{ tsm_script_mode }}"
        set_results_status: "{{ tsm_status }}"

