---
- name: "Initialisation du rôle maître ips_toolbox_tsm"
  ansible.builtin.set_fact:
    tsm_component: "tsm"
    tsm_role_name: "ips_toolbox_tsm"

- name: "Construction du nom de fichier de tâche TSM selon l'OS"
  ansible.builtin.set_fact:
    tsm_task_file: "{{ tsm_operation | default('detect') }}_{{ ansible_system }}_tsm.yml"

- name: "Vérification de l'existence du fichier de tâche TSM"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ tsm_task_file }}"
  register: tsm_task_exists
  delegate_to: localhost

- name: "Exécution de la tâche TSM spécifique à l'OS"
  include_tasks: "{{ tsm_task_file }}"
  when: tsm_task_exists.stat.exists
  ignore_errors: true

- name: "Fallback - Tâche générique TSM si spécifique introuvable"
  include_tasks: "detect_generic_tsm.yml"
  when: not tsm_task_exists.stat.exists
  ignore_errors: true

- name: "Affichage du statut d'exécution TSM"
  ansible.builtin.debug:
    msg:
      - "Rôle TSM maître exécuté"
      - "Fichier: {{ tsm_task_file if tsm_task_exists.stat.exists else 'detect_generic_tsm.yml' }}"
      - "OS: {{ ansible_system }}"
      - "Opération: {{ tsm_operation | default('detect') }}"
