---

- name: check liberty base installation
  shell: test -f /apps/WebSphere*/LibertyiBase/bin/productInfo 
  register: liberty_install    
  changed_when: false
  failed_when: false

- name: check liberty version
  shell: |
        . ~was/.profile
        /apps/WebSphere*/LibertyBase/bin/productInfo version | grep version | awk '{print $3}'
  become: true
  become_user: was
  become_method: su
  register: wasVersion
  changed_when: false
  failed_when: false
  when: liberty_install.rc == 0

- name: Format to Json when liberty base is installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"yes\" ,\"version\": \"{{ wasVersion.stdout }}\" }"
  when: liberty_install.rc == 0

- name: Format to Json when liberty base is not installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"no\" ,\"version\": \"\" }"
  when: liberty_install.rc != 0

- name: set result output for liberty check
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: ""
    set_results_value: "{{ tmp_json | to_json | from_json }}" 
    set_results_component: "{{ libertybase_component }}"
    set_results_operation: "{{ libertybase_operation }}"
    set_results_role_name: "{{ libertybase_role_name }}"
    set_results_result_name: "{{ libertybase_result_name }}"
    set_results_status: "OK"


