---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - libertybase_xml_file != ""
    - libertybase_layer != ""
  msg: "One of this mandatory variable is missing: libertybase_xml_file, libertybase_layer"

- name: stop play when layer is not conform
  ansible.builtin.assert:
  that:
    - libertybase_layer == "prez" or libertybase_layer == "biz"
  msg: "The libertybase_layer value is not valid"

- name: Check toolbox version
  shell: test -f /apps/toolboxes/version && cat /apps/toolboxes/version | awk -F '|' '{print $2}' | sed 's/\.//g' || echo "0"
  register: tbxversion
  changed_when: false

- name: Copy WAS_Detect script on the remote server
  ansible.builtin.copy:
  src: WAS_Detect.ksh
  dest: /apps/toolboxes/web/CreateEnvWas/param
  mode: '0755'
  changed_when: false
  when: (tbxversion.stdout_lines[0]|int >= (1920|int))

- name: "Check Libertybase installation"
  shell: "/apps/toolboxes/web/CreateEnvWas/param/WAS_Detect.ksh wlb | grep WLB | awk -F '=' '{print $2}'"
  register: libertybase_install
  changed_when: false
  failed_when: "'Yes' not in libertybase_install.stdout"
  when: (tbxversion.stdout_lines[0]|int >= (1920|int))

- name: Copy the xml file create Sybase Datasource on the remote server
  ansible.builtin.copy:
  src: "{{ libertybase_xml_file }}"
  dest: /apps/toolboxes/web/CreateEnvWas/param
  owner: was
  group: web
  mode: u=rw,g=r,o=r
  changed_when: false
  when: (tbxversion.stdout_lines[0]|int >= (1920|int))

- name: Create Sybase Datasource 
  shell: /apps/toolboxes/web/CreateEnvWas/createEnvWasCMD.ksh dsywl {{ libertybase_layer }} y
  register: result_create_env
  changed_when: "'already exists' not in result_create_env.stdout"
  failed_when: false
  when: (tbxversion.stdout_lines[0]|int >= (1920|int))

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_component: "{{ libertybase_component }}"
    set_results_operation: "{{ libertybase_operation }}"
    set_results_role_name: "{{ libertybase_role_name }}"
    set_results_result_name: "{{ libertybase_result_name }}"
    set_results_item: "{{ libertybase_item }}"
    set_results_state: "OK"
    set_results_status: "{% if tbxversion.stdout_lines[0]|int >= (1920|int) %}\

                            {% if result_create_env.rc != 0 %}\

                              {% if 'already exists' not in result_create_env.stdout %}\

                                KO\

                              {% else %}\

                                OK\

                              {% endif %}\

                            {% else %}\

                              OK\

                            {% endif %}\

                          {% else %}\

                            KO\

                          {% endif %}"
    set_results_value: "{% if tbxversion.stdout_lines[0]|int >= (1920|int) %}\

                            {% if result_create_env.rc != 0 %}\

                                {% if 'already exists' not in result_create_env.stdout %}\

                                  Error encountered  during Sybase Datasource creation\

                                {% else %}\

                                  Sybase Datasource successfully created\

                                {% endif %}\

                            {% else %}\

                              Sybase Datasource successfully created\

                            {% endif %}\

                          {% else %}\

                            Toolbox is under required version (19.2.0) to create Sybase Datasource\

                          {% endif %}"

