---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
  that:
    - libertybase_item != ""
  msg: "libertybase_item variable is missing"

- name: copy Manage script
  ansible.builtin.copy:
    src: WAS_Manage.ksh 
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: copy Manage script2
  ansible.builtin.copy:
    src: wasstartstop_cmd.ksh
    dest: "/applis/"
    mode: '0755'
  changed_when: false

- name: "restarting {{ libertybase_item }}"
  shell: "/applis/wasstartstop_cmd.ksh restart wlb {{ libertybase_item }}"
  register: restart_lib_result
  changed_when: "'successfully' in restart_lib_result.stdout"
  failed_when: false

- set_fact:
    state_value_json: ""
    final_state: "unknown"
    final_status: "OK"

- set_fact:
    state_value_json: "not restarted"
    final_status: "KO"
  when:
  - "'No JVM found' in restart_lib_result.stdout"

- set_fact:
    state_value_json: "{% if line_json.split(' ')[-1] != \"service\" %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"service\": \"no\" ,\"status\": \"{% if line_json.split(' ')[4] == \"RESTARTED\" %}restarted\"{% else %}not restarted\"{% endif %} }{% else %}{{ state_value_json }}, { \"application_server\": \"{{ line_json.split(' ')[1] }}\" ,\"service\": \"{{ line_json.split(' ')[7] }}\" ,\"status\": \"{% if line_json.split(' ')[4] == \"RESTARTED\" %}restarted\"{% else %}not restarted\"{% endif %} }{% endif %}"
  loop: "{{ restart_lib_result.stdout_lines }}"
  loop_control:
    loop_var: line_json
  when:
  - "'No JVM found' not in restart_lib_result.stdout"

- set_fact:
    final_state: "restarted"
  when: "'not restarted' not in state_value_json"

- set_fact:
    final_state: "not restarted"
    final_status: "KO"
  when: "'not restarted' in state_value_json"

- name: set results output
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_component: "{{ libertybase_component }}"
    set_results_operation: "{{ libertybase_operation }}"
    set_results_role_name: "{{ libertybase_role_name }}"
    set_results_result_name: "{{ libertybase_result_name }}"
    set_results_item: "{{ libertybase_item }}"
    set_results_state: "{{ final_state }}"
    set_results_status: "{{ final_status }}"
    set_results_value: "{% if 'No JVM found' in restart_lib_result.stdout %}\

                          application server not found\

                        {% else %}\

                          [ {{ state_value_json[1:] }} ]\

                        {% endif %}"

