---

- name: check installation
  win_check_service:
    name: MSSQL*
  register: check_install

- name: check version
  script: SQLVersion.ps1
  register: check_version
  when: check_install.services_info[0] is defined
  changed_when: false

- name: Format to Json when sqlserver is installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"yes\" ,\"version\": \"{{ check_version.stdout_lines[0] }}\" }"
  when:  check_install.services_info[0] is defined

- name: Format to Json when sqlserver is not installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"no\" ,\"version\": \"\" }"
  when: check_install.services_info[0] is not defined

- name: format installation status
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: ""
    set_results_value: "{{ tmp_json | to_json | from_json }}"
    set_results_component: "{{ sqlserver_component }}"
    set_results_operation: "{{ sqlserver_operation }}"
    set_results_role_name: "{{ sqlserver_role_name }}"
    set_results_result_name: "{{ sqlserver_result_name }}"
    set_results_status: "OK"



