---

- name: check Autosys version
  shell: cd /apps/waae/ && output=$(ls | grep [0-9]*.[0-9]*) && cd $output && cd SystemAgent/ && cd $(hostname) && ./cybAgent -v | grep -e Build | sed 's/^ *//'
  register: AutosysVersion
  changed_when: false
  failed_when: false

- name: Format to Json when autosys is installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"yes\" ,\"version\": \"{{ AutosysVersion.stdout }}\" }"
  when:  AutosysVersion.rc == 0

- name: Format to Json when autosys is not installed
  ansible.builtin.set_fact:
    tmp_json: "{ \"installed\": \"no\" ,\"version\": \"\" }"
  when: AutosysVersion.rc !=0

    
- name: set result output for autosys check
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "info"
    set_results_item: ""
    set_results_value: "{{ tmp_json | to_json | from_json }}"
    set_results_component: "{{ autosys_component }}"
    set_results_operation: "{{ autosys_operation }}"
    set_results_role_name: "{{ autosys_role_name }}"
    set_results_result_name: "{{ autosys_result_name }}"
    set_results_status:
      "{% if AutosysVersion.rc == 0 %}\

        {% if AutosysVersion.stdout == '' %}\

          KO\

        {% else %}\

        OK\

        {% endif %}\

      {% else %}\

      OK\

      {% endif %}"


