---
- name: "Collecte de l'uptime système via /proc/uptime"
  ansible.builtin.shell: |
    uptime_seconds=$(cat /proc/uptime | cut -d' ' -f1 | cut -d'.' -f1)
    uptime_days=$((uptime_seconds / 86400))
    echo "$uptime_days"
  register: system_uptime_days_raw
  changed_when: false
  failed_when: false

- name: "Conversion de l'uptime en jours (type int)"
  ansible.builtin.set_fact:
    system_uptime_days: "{{ (system_uptime_days_raw.stdout | default('0')) | int }}"

- name: "Collecte de la date système actuelle"
  ansible.builtin.set_fact:
    current_date: "{{ ansible_date_time.iso8601 }}"
    current_epoch: "{{ ansible_date_time.epoch | int }}"

- name: "Calcul de la date de dernier redémarrage"
  ansible.builtin.set_fact:
    last_boot_epoch: "{{ current_epoch - (system_uptime_days * 86400) }}"

- name: "Conversion de la date de dernier redémarrage"
  ansible.builtin.shell: |
    date -d "@{{ last_boot_epoch }}" "+%Y-%m-%d %H:%M:%S"
  register: last_boot_date_formatted
  changed_when: false
  failed_when: false

- name: "Vérification de la conformité uptime (< 90 jours)"
  ansible.builtin.set_fact:
    uptime_compliant: "{{ system_uptime_days < (system_uptime_limit | default(90)) }}"
    uptime_status: >-
      {% if system_uptime_days < (system_uptime_limit | default(90)) %}
      CONFORME
      {% else %}
      NON CONFORME - REDÉMARRAGE REQUIS
      {% endif %}

- name: "Affichage détaillé de l'uptime système"
  ansible.builtin.debug:
    msg:
      - "=== VÉRIFICATION UPTIME SYSTÈME ==="
      - "Date actuelle: {{ current_date }}"
      - "Uptime en jours: {{ system_uptime_days }} jours"
      - "Limite configurée: {{ system_uptime_limit | default(90) }} jours"
      - "Dernier redémarrage: {{ last_boot_date_formatted.stdout | default('Date inconnue') }}"
      - "Statut conformité: {{ uptime_status }}"
      - "Action requise: {{ 'Aucune' if uptime_compliant else 'Planifier un redémarrage' }}"
      - "=== FIN VÉRIFICATION UPTIME ==="

- name: "Enregistrement du résultat uptime"
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_state: "{{ 'OK' if uptime_compliant else 'WARNING' }}"
    set_results_component: "system"
    set_results_operation: "uptime"
    set_results_value: >-
      Uptime: {{ system_uptime_days }} jours (limite: {{ system_uptime_limit | default(90) }}) - 
      {{ 'CONFORME' if uptime_compliant else 'REDÉMARRAGE REQUIS' }}
  ignore_errors: true

- name: "Alerte uptime dépassé"
  ansible.builtin.debug:
    msg:
      - "⚠️  ALERTE UPTIME DÉPASSÉ ⚠️"
      - "Le serveur {{ inventory_hostname }} fonctionne depuis {{ system_uptime_days }} jours"
      - "Limite configurée: {{ system_uptime_limit | default(90) }} jours"
      - "Un redémarrage doit être planifié selon les règles BP21"
  when: not uptime_compliant
