---
- name: "Initialisation du rôle maître ips_toolbox_services"
  set_fact:
    services_component: "services"
    services_role_name: "ips_toolbox_services"

- name: "Construction du nom de fichier de tâche services selon l'OS"
  set_fact:
    services_task_file: "{{ services_operation | default('manage') }}_{{ ansible_system }}_services.yml"

- name: "Vérification de l'existence du fichier de tâche services"
  stat:
    path: "{{ role_path }}/tasks/{{ services_task_file }}"
  register: services_task_exists
  delegate_to: localhost
  failed_when: false

- name: "Exécution de la tâche services spécifique à l'OS"
  include_tasks: "{{ services_task_file }}"
  when: services_task_exists.stat.exists
  ignore_errors: true

- name: "Fallback - Tâche générique services si spécifique introuvable"
  include_tasks: "manage_generic_services.yml"
  when: not services_task_exists.stat.exists
  ignore_errors: true

- name: "Affichage du statut d'exécution services"
  debug:
    msg:
      - "Rôle services maître exécuté"
      - "Fichier: {{ services_task_file if services_task_exists.stat.exists else 'manage_generic_services.yml' }}"
      - "OS: {{ ansible_system }}"
      - "Opération: {{ services_operation | default('manage') }}"
