---

- name: stop play when a mandatory variable is missing
  ansible.builtin.assert:
    that:
      - services_item != ""
    msg: "services_item variable is missing"

- name: Begin stop service

  block:

  - name : stop service
    win_service:
      state: stopped
      name: "{{ services_item }}"
    register: stop_service
    changed_when:
      - stop_service.changed == True

  - name: set facts
    ansible.builtin.set_fact:
      services_state: "stopped"
      services_value: ""
      services_status: "OK"

  rescue:
    - name: ansible failure
      ansible.builtin.set_fact:
        services_state: "not stopped"
        services_value: "{{ stop_service.msg }}"
        services_status: "KO"

- name: set results output for services
  ansible.builtin.include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state: "{{ services_state }}"
    set_results_item: "{{ services_item }}"
    set_results_value: "{{ services_value }}"
    set_results_component: "{{ services_component }}"
    set_results_operation: "{{ services_operation }}"
    set_results_role_name: "{{ services_role_name }}"
    set_results_result_name: "{{ services_result_name }}"
    set_results_status: "{{ services_status }}"

