---
- name: Web Module Tasks
  hosts: "{{ target_hostname }}"
  gather_facts: yes
  become: yes

  tasks:
    - name: Detect WAS type
      shell: |
        if [ -f "{{ websphere.profile_root }}/bin/server" ]; then echo "liberty"
        elif [ -f "{{ websphere.profile_root }}/bin/startServer.sh" ]; then echo "was"
        else echo "none"; fi
      register: was_type_detected
      changed_when: false

    - name: Set toolbox vars
      set_fact:
        toolboxes_component: "web"
        toolboxes_operation: "{{ was_type_detected.stdout }}"
        toolboxes_role_name: "ips_toolbox_{{ was_type_detected.stdout }}"
        toolboxes_task_file_name: "{{ was_type_detected.stdout }}.yml"

    - name: Execute web toolbox
      include_role:
        name: "{{ toolboxes_role_name }}"
      vars:
        toolboxes_component: "{{ toolboxes_component }}"
        toolboxes_operation: "{{ toolboxes_operation }}"
        toolboxes_role_name: "{{ toolboxes_role_name }}"
        toolboxes_task_file_name: "{{ toolboxes_task_file_name }}"

  rescue:
    - name: Report web error
      include_role:
        name: ips_toolbox_set_results
      vars:
        set_results_state: "error"
        set_results_component: "web"
        set_results_operation: "{{ was_type_detected.stdout }}"
        set_results_role_name: "{{ toolboxes_role_name }}"
        set_results_status: "KO"
        set_results_value: "Web module failed"
