# Ajout de résultats aux facts
---
- name: "Calcul de l'uptime en jours (conversion de type corrigée)"
  shell: "awk '{print int($1/86400)}' < /proc/uptime"
  register: uptime_days_raw
  changed_when: false
  when: ansible_os_family != "Windows"

- name: "Calcul de l'uptime Windows"
  win_shell: |
    $uptime = (Get-WmiObject -Class Win32_OperatingSystem).LastBootUpTime
    $bootTime = [System.Management.ManagementDateTimeConverter]::ToDateTime($uptime)
    $currentTime = Get-Date
    $uptimeDays = [math]::Floor(($currentTime - $bootTime).TotalDays)
    Write-Output $uptimeDays
  register: uptime_days_raw_win
  changed_when: false
  when: ansible_os_family == "Windows"

- name: "Initialisation de la variable uptime_days avec conversion de type"
  set_fact:
    uptime_days_int: "{{ (uptime_days_raw.stdout | default('0')) | int }}"
  when: ansible_os_family != "Windows"

- name: "Initialisation de la variable uptime_days Windows"
  set_fact:
    uptime_days_int: "{{ (uptime_days_raw_win.stdout | default('0')) | int }}"
  when: ansible_os_family == "Windows"

- name: "Formatage de l'uptime (corrigé avec conversion de type)"
  set_fact:
    uptime_summary: >-
      {% if uptime_days_int < 1 %}
      0 day
      {% else %}
      {{ uptime_days_int }} days
      {% endif %}

- name: "Initialisation des résultats temporaires"
  set_fact:
    temp_result:
      component: "{{ set_results_component | default('unknown') }}"
      operation: "{{ set_results_operation | default('unknown') }}"
      state: "{{ set_results_state | default('OK') }}"
      value: "{{ set_results_value | default('No value') }}"
      timestamp: "{{ ansible_date_time.iso8601 }}"
      hostname: "{{ inventory_hostname }}"
      uptime: "{{ uptime_summary }}"

- name: "Ajout du résultat aux facts système"
  set_fact:
    ips_toolbox_results: "{{ ips_toolbox_results | default([]) + [temp_result] }}"

- name: "Affichage du résultat ajouté"
  debug:
    msg:
      - "Résultat ajouté aux facts:"
      - "  - Composant: {{ temp_result.component }}"
      - "  - Opération: {{ temp_result.operation }}"
      - "  - État: {{ temp_result.state }}"
      - "  - Valeur: {{ temp_result.value }}"
      - "  - Uptime: {{ temp_result.uptime }}"
      - "  - Timestamp: {{ temp_result.timestamp }}"
