---

###
### playbook chk_bkp_appli.yml
### purpose: Check if the applicative TSM Backup is conform
###
### created by:    PERIN David For ITG/IPS/PPM02, 31/05/2018
### modifications: (name, date, purpose)
#### NAVARRO Wilfried 07/03/2019 bugfix "banner" display
#####

- name: check backup appli
  script: check_backup_appli.ksh {{ backup_depth }}
  register: chk_bkp_appli
  changed_when: false
  failed_when: false

- name: set results output for tsm applicative
  include_role:
    name: ips_toolbox_set_results
  vars:
    set_results_status: "OK"
    set_results_item: ""
    set_results_value: "\

           {% if chk_bkp_appli.rc == 0 %}\

             OK\

           {% else %}\

             {{ chk_bkp_appli.stdout_lines | last }}\

           {% endif %}"
    set_results_component: "{{ backup_component }}"
    set_results_operation: "{{ backup_operation }}"
    set_results_role_name: "{{ backup_role_name }}"
    set_results_result_name: "{{ backup_result_name }}"
    set_results_state: "\

           {% if chk_bkp_appli.rc == 0 %}\

             compliant\

           {% else %}\

             not compliant\

           {% endif %}"
   

