---

###
#### playbook chk_bkp_sys.yml
#### purpose: Check if the system TSM Backup is conform
####
#### created by:    PERIN David For ITG/IPS/PPM02, 31/05/2018
#### modifications: (name, date, purpose)
#### NAVARRO Wilfried 07/03/2019 bugfix "banner" display
######

- name: Check tsm installed
  find:
    paths: "/usr/tivoli/tsm/client/ba"
    patterns: "dsmc"
    recurse: yes
  register: tsmbinchk

- name: check backup system
  script: check_backup_sys.ksh
  register: chkbkpsys_date
  changed_when: false
  failed_when: false
  environment:
    DSM_DIR: /apps/sys/admin/tsm_system
    DSM_CONFIG: /apps/sys/admin/tsm_system/dsm.opt
  when: tsmbinchk.matched > 0

- name: set results output for tsm system backup
  include_role:
    name: ips_toolbox_set_results
  vars:
    name: results
    set_results_state: "info"
    set_results_item: "TSM backup system"
    set_results_value: "{% if tsmbinchk.matched == 0 %}\

                           KO -- TSM is not installed\

                        {% else %}\

                           {% if chkbkpsys_date.stderr | regex_search('ANS1092W') %}\

                              KO -- No system backup detected\

                           {% else %}\

                             {% if chkbkpsys_date.stdout != '' %}\

                                {% if (( (ansible_date_time.date | to_datetime('%Y-%m-%d') - chkbkpsys_date.stdout_lines | last | to_datetime('%Y-%m-%d')).total_seconds() / 86400 ) | int) > 15 %}\

                                   KO -- The last backup is older than 15 days, it has been performed the {{ chkbkpsys_date.stdout_lines | last }} (YYYY-MM-DD)\

                                {% else %}\

                                   OK -- The last backup is not older than 15 days, it has been performed the {{ chkbkpsys_date.stdout_lines | last }} (YYYY-MM-DD)\

                                {% endif %}\

                             {% else %}\

                                KO -- No system backup detected\

                             {% endif %}\

                           {% endif %}\

                        {% endif %}"
    set_results_component: "{{ backup_component }}"
    set_results_operation: "{{ backup_operation }}"
    set_results_role_name: "{{ backup_role_name }}"
    set_results_result_name: "{{ backup_result_name }}"
    set_results_status: "OK"

