---
# Main tasks for ips_toolbox_bigfix role - Patch Management

- name: Check if BigFix is installed
  stat:
    path: "{{ bigfix.client_path }}"
  register: bigfix_installed

- name: Fail if BigFix not installed
  fail:
    msg: "BigFix is not installed on this server"
  when: not bigfix_installed.stat.exists

- name: Get BigFix agent status
  include_tasks: agent_status.yml
  tags:
    - status

- name: Manage BigFix agent
  include_tasks: manage_agent.yml
  when: agent_action is defined
  tags:
    - agent
    - service
